// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	jwt "fukuro-reserve/pkg/utils/jwt"

	mock "github.com/stretchr/testify/mock"

	models "auth/internal/repository/postgres/models"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// LoginByEmail provides a mock function with given fields: ctx, email, pass
func (_m *MockService) LoginByEmail(ctx context.Context, email string, pass string) (*jwt.Token, error) {
	ret := _m.Called(ctx, email, pass)

	if len(ret) == 0 {
		panic("no return value specified for LoginByEmail")
	}

	var r0 *jwt.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*jwt.Token, error)); ok {
		return rf(ctx, email, pass)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *jwt.Token); ok {
		r0 = rf(ctx, email, pass)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, pass)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_LoginByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginByEmail'
type MockService_LoginByEmail_Call struct {
	*mock.Call
}

// LoginByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - pass string
func (_e *MockService_Expecter) LoginByEmail(ctx interface{}, email interface{}, pass interface{}) *MockService_LoginByEmail_Call {
	return &MockService_LoginByEmail_Call{Call: _e.mock.On("LoginByEmail", ctx, email, pass)}
}

func (_c *MockService_LoginByEmail_Call) Run(run func(ctx context.Context, email string, pass string)) *MockService_LoginByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_LoginByEmail_Call) Return(_a0 *jwt.Token, _a1 error) *MockService_LoginByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_LoginByEmail_Call) RunAndReturn(run func(context.Context, string, string) (*jwt.Token, error)) *MockService_LoginByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: token
func (_m *MockService) RefreshToken(token *jwt.Token) (*jwt.Token, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *jwt.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwt.Token) (*jwt.Token, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Token) *jwt.Token); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(*jwt.Token) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - token *jwt.Token
func (_e *MockService_Expecter) RefreshToken(token interface{}) *MockService_RefreshToken_Call {
	return &MockService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", token)}
}

func (_c *MockService_RefreshToken_Call) Run(run func(token *jwt.Token)) *MockService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*jwt.Token))
	})
	return _c
}

func (_c *MockService_RefreshToken_Call) Return(_a0 *jwt.Token, _a1 error) *MockService_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_RefreshToken_Call) RunAndReturn(run func(*jwt.Token) (*jwt.Token, error)) *MockService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterByEmail provides a mock function with given fields: ctx, email, password
func (_m *MockService) RegisterByEmail(ctx context.Context, email string, password string) (*jwt.Token, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterByEmail")
	}

	var r0 *jwt.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*jwt.Token, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *jwt.Token); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_RegisterByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterByEmail'
type MockService_RegisterByEmail_Call struct {
	*mock.Call
}

// RegisterByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockService_Expecter) RegisterByEmail(ctx interface{}, email interface{}, password interface{}) *MockService_RegisterByEmail_Call {
	return &MockService_RegisterByEmail_Call{Call: _e.mock.On("RegisterByEmail", ctx, email, password)}
}

func (_c *MockService_RegisterByEmail_Call) Run(run func(ctx context.Context, email string, password string)) *MockService_RegisterByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_RegisterByEmail_Call) Return(_a0 *jwt.Token, _a1 error) *MockService_RegisterByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_RegisterByEmail_Call) RunAndReturn(run func(context.Context, string, string) (*jwt.Token, error)) *MockService_RegisterByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UserCreate provides a mock function with given fields: ctx, user
func (_m *MockService) UserCreate(ctx context.Context, user models.UserCreate) (*models.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UserCreate")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserCreate) (*models.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserCreate) *models.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserCreate) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UserCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserCreate'
type MockService_UserCreate_Call struct {
	*mock.Call
}

// UserCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - user models.UserCreate
func (_e *MockService_Expecter) UserCreate(ctx interface{}, user interface{}) *MockService_UserCreate_Call {
	return &MockService_UserCreate_Call{Call: _e.mock.On("UserCreate", ctx, user)}
}

func (_c *MockService_UserCreate_Call) Run(run func(ctx context.Context, user models.UserCreate)) *MockService_UserCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserCreate))
	})
	return _c
}

func (_c *MockService_UserCreate_Call) Return(_a0 *models.User, _a1 error) *MockService_UserCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UserCreate_Call) RunAndReturn(run func(context.Context, models.UserCreate) (*models.User, error)) *MockService_UserCreate_Call {
	_c.Call.Return(run)
	return _c
}

// UserDeleteByID provides a mock function with given fields: ctx, id
func (_m *MockService) UserDeleteByID(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserDeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_UserDeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserDeleteByID'
type MockService_UserDeleteByID_Call struct {
	*mock.Call
}

// UserDeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockService_Expecter) UserDeleteByID(ctx interface{}, id interface{}) *MockService_UserDeleteByID_Call {
	return &MockService_UserDeleteByID_Call{Call: _e.mock.On("UserDeleteByID", ctx, id)}
}

func (_c *MockService_UserDeleteByID_Call) Run(run func(ctx context.Context, id int64)) *MockService_UserDeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_UserDeleteByID_Call) Return(_a0 error) *MockService_UserDeleteByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UserDeleteByID_Call) RunAndReturn(run func(context.Context, int64) error) *MockService_UserDeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// UserGetAll provides a mock function with given fields: ctx, limit, offset
func (_m *MockService) UserGetAll(ctx context.Context, limit uint64, offset uint64) ([]models.User, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for UserGetAll")
	}

	var r0 []models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]models.User, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) []models.User); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UserGetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserGetAll'
type MockService_UserGetAll_Call struct {
	*mock.Call
}

// UserGetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - limit uint64
//   - offset uint64
func (_e *MockService_Expecter) UserGetAll(ctx interface{}, limit interface{}, offset interface{}) *MockService_UserGetAll_Call {
	return &MockService_UserGetAll_Call{Call: _e.mock.On("UserGetAll", ctx, limit, offset)}
}

func (_c *MockService_UserGetAll_Call) Run(run func(ctx context.Context, limit uint64, offset uint64)) *MockService_UserGetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *MockService_UserGetAll_Call) Return(_a0 []models.User, _a1 error) *MockService_UserGetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UserGetAll_Call) RunAndReturn(run func(context.Context, uint64, uint64) ([]models.User, error)) *MockService_UserGetAll_Call {
	_c.Call.Return(run)
	return _c
}

// UserGetByID provides a mock function with given fields: ctx, id
func (_m *MockService) UserGetByID(ctx context.Context, id int64) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserGetByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UserGetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserGetByID'
type MockService_UserGetByID_Call struct {
	*mock.Call
}

// UserGetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockService_Expecter) UserGetByID(ctx interface{}, id interface{}) *MockService_UserGetByID_Call {
	return &MockService_UserGetByID_Call{Call: _e.mock.On("UserGetByID", ctx, id)}
}

func (_c *MockService_UserGetByID_Call) Run(run func(ctx context.Context, id int64)) *MockService_UserGetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_UserGetByID_Call) Return(_a0 *models.User, _a1 error) *MockService_UserGetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UserGetByID_Call) RunAndReturn(run func(context.Context, int64) (*models.User, error)) *MockService_UserGetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UserUpdateByID provides a mock function with given fields: ctx, user
func (_m *MockService) UserUpdateByID(ctx context.Context, user *models.User) (*models.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UserUpdateByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) (*models.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) *models.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UserUpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserUpdateByID'
type MockService_UserUpdateByID_Call struct {
	*mock.Call
}

// UserUpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockService_Expecter) UserUpdateByID(ctx interface{}, user interface{}) *MockService_UserUpdateByID_Call {
	return &MockService_UserUpdateByID_Call{Call: _e.mock.On("UserUpdateByID", ctx, user)}
}

func (_c *MockService_UserUpdateByID_Call) Run(run func(ctx context.Context, user *models.User)) *MockService_UserUpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockService_UserUpdateByID_Call) Return(_a0 *models.User, _a1 error) *MockService_UserUpdateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UserUpdateByID_Call) RunAndReturn(run func(context.Context, *models.User) (*models.User, error)) *MockService_UserUpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
