syntax = "proto3";

package booking.v1;

option go_package = "api/booking/v1;bookingv1";

import "buf/validate/validate.proto";
import "booking/v1/models/booking.proto";

message GetBookingRequest {
  string id = 1 [
    (buf.validate.field).string.uuid = true
  ];
  string country_code = 2 [
    (buf.validate.field).string.pattern = "^[a-z]{2}$"
  ];
  string city_slug = 3 [
    (buf.validate.field).string.pattern = "^[a-z0-9]+(-[a-z0-9]+)*$"
  ];
}

message GetBookingResponse {
  Booking booking = 1;
}
