version: "2"
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - gosec
    - revive
    - misspell
    - unconvert
    - bodyclose
    - prealloc
    - errorlint

  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.Tx).Rollback

    govet:
      enable:
        - fieldalignment

    revive:
      rules:
        - name: var-naming
          disabled: true

    gosec:
      excludes:
        - G101

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$