version: '3'

tasks:
  run:
    desc: "Run (task run service=auth|hotel|booking)"
    cmd: "go run services/{{.service}}/cmd/app/main.go"
    env:
      CONFIG_PATH: "services/auth/config/local.yaml"
    requires:
      vars: [service]

  build:
    desc: "Build (task build service=auth|hotel|booking)"
    cmds:
      - go build -o build/{{.service}}-service services/{{.service}}/cmd/app/main.go
    requires:
      vars: [service]

  mock-gen:
    desc: "Generate mocks (task mock-gen service=auth|hotel|booking)"
    dir: services/{{.service}}
    cmds:
      - rm -rf internal/mocks
      - mockery
    requires:
      vars: [service]

  swag-gen:
    desc: "Generate Swagger docs (task swag-gen service=auth|hotel|booking)"
    dir: services/{{.service}}
    cmds:
      - swag init -g cmd/app/main.go --output docs
    requires:
      vars: [service]

  test-unit-handler:
    desc: "Run unit tests (task test-unit-handler service=auth|hotel|booking)"
    cmds:
      - go test ./services/{{.service}}/internal/http/handler/ -v
    requires:
      vars: [service]

  postgres-up:
    desc: "Start PostgreSQL container"
    cmds:
      - docker compose --env-file .env -f docker/postgres.yaml up -d

  postgres-down:
    desc: "Stop PostgreSQL container"
    cmds:
      - docker compose --env-file .env -f docker/postgres.yaml down

  goose:
    dotenv: [".env.dev"]
    desc: "Goose migrations (task goose service=auth|hotel|booking mode=status|up|down)"
    cmd: |
      goose -dir services/{{.service}}/migrations postgres \
        "host=${POSTGRES_HOST} \
        port=${POSTGRES_PORT} \
        user=${POSTGRES_USER} \
        password=${POSTGRES_PASSWORD} \
        dbname={{.service}} \
        sslmode=disable" \
        {{default "status" .mode}}
    requires:
      vars: [service]

  goose-gen:
    desc: "Goose gen sql schema (task goose-gen service=auth|hotel|booking)"
    cmd: goose create {{.title}} sql --dir services/{{.service}}/migrations
    requires:
      vars: [service]