// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/rpc/user/delete_user.proto

package userv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_v1_rpc_user_delete_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_rpc_user_delete_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_rpc_user_delete_user_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_user_v1_rpc_user_delete_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_rpc_user_delete_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_rpc_user_delete_user_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_user_v1_rpc_user_delete_user_proto protoreflect.FileDescriptor

const file_user_v1_rpc_user_delete_user_proto_rawDesc = "" +
	"\n" +
	"\"user/v1/rpc/user/delete_user.proto\x12\auser.v1\x1a\x1bbuf/validate/validate.proto\"/\n" +
	"\x11DeleteUserRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\x03B\n" +
	"\xbaH\a\xc8\x01\x01\"\x02(\x01R\x02id\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\x14Z\x12api/user/v1;userv1b\x06proto3"

var (
	file_user_v1_rpc_user_delete_user_proto_rawDescOnce sync.Once
	file_user_v1_rpc_user_delete_user_proto_rawDescData []byte
)

func file_user_v1_rpc_user_delete_user_proto_rawDescGZIP() []byte {
	file_user_v1_rpc_user_delete_user_proto_rawDescOnce.Do(func() {
		file_user_v1_rpc_user_delete_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_rpc_user_delete_user_proto_rawDesc), len(file_user_v1_rpc_user_delete_user_proto_rawDesc)))
	})
	return file_user_v1_rpc_user_delete_user_proto_rawDescData
}

var file_user_v1_rpc_user_delete_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_v1_rpc_user_delete_user_proto_goTypes = []any{
	(*DeleteUserRequest)(nil),  // 0: user.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil), // 1: user.v1.DeleteUserResponse
}
var file_user_v1_rpc_user_delete_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_rpc_user_delete_user_proto_init() }
func file_user_v1_rpc_user_delete_user_proto_init() {
	if File_user_v1_rpc_user_delete_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_rpc_user_delete_user_proto_rawDesc), len(file_user_v1_rpc_user_delete_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_rpc_user_delete_user_proto_goTypes,
		DependencyIndexes: file_user_v1_rpc_user_delete_user_proto_depIdxs,
		MessageInfos:      file_user_v1_rpc_user_delete_user_proto_msgTypes,
	}.Build()
	File_user_v1_rpc_user_delete_user_proto = out.File
	file_user_v1_rpc_user_delete_user_proto_goTypes = nil
	file_user_v1_rpc_user_delete_user_proto_depIdxs = nil
}
