// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/rpc/user/get_users.proto

package userv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_user_v1_rpc_user_get_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_rpc_user_get_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_rpc_user_get_users_proto_rawDescGZIP(), []int{0}
}

func (x *GetUsersRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUsersRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserShort           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint64                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_user_v1_rpc_user_get_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_rpc_user_get_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_rpc_user_get_users_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsersResponse) GetUsers() []*UserShort {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetUsersResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetUsersResponse) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUsersResponse) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_user_v1_rpc_user_get_users_proto protoreflect.FileDescriptor

const file_user_v1_rpc_user_get_users_proto_rawDesc = "" +
	"\n" +
	" user/v1/rpc/user/get_users.proto\x12\auser.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19user/v1/models/user.proto\"O\n" +
	"\x0fGetUsersRequest\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\x04B\a\xbaH\x042\x02(\x01R\x04page\x12\x1f\n" +
	"\x05limit\x18\x02 \x01(\x04B\t\xbaH\x062\x04\x18d(\x01R\x05limit\"\x87\x01\n" +
	"\x10GetUsersResponse\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.user.v1.UserShortR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x04R\x05limitB\x14Z\x12api/user/v1;userv1b\x06proto3"

var (
	file_user_v1_rpc_user_get_users_proto_rawDescOnce sync.Once
	file_user_v1_rpc_user_get_users_proto_rawDescData []byte
)

func file_user_v1_rpc_user_get_users_proto_rawDescGZIP() []byte {
	file_user_v1_rpc_user_get_users_proto_rawDescOnce.Do(func() {
		file_user_v1_rpc_user_get_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_rpc_user_get_users_proto_rawDesc), len(file_user_v1_rpc_user_get_users_proto_rawDesc)))
	})
	return file_user_v1_rpc_user_get_users_proto_rawDescData
}

var file_user_v1_rpc_user_get_users_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_v1_rpc_user_get_users_proto_goTypes = []any{
	(*GetUsersRequest)(nil),  // 0: user.v1.GetUsersRequest
	(*GetUsersResponse)(nil), // 1: user.v1.GetUsersResponse
	(*UserShort)(nil),        // 2: user.v1.UserShort
}
var file_user_v1_rpc_user_get_users_proto_depIdxs = []int32{
	2, // 0: user.v1.GetUsersResponse.users:type_name -> user.v1.UserShort
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_v1_rpc_user_get_users_proto_init() }
func file_user_v1_rpc_user_get_users_proto_init() {
	if File_user_v1_rpc_user_get_users_proto != nil {
		return
	}
	file_user_v1_models_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_rpc_user_get_users_proto_rawDesc), len(file_user_v1_rpc_user_get_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_rpc_user_get_users_proto_goTypes,
		DependencyIndexes: file_user_v1_rpc_user_get_users_proto_depIdxs,
		MessageInfos:      file_user_v1_rpc_user_get_users_proto_msgTypes,
	}.Build()
	File_user_v1_rpc_user_get_users_proto = out.File
	file_user_v1_rpc_user_get_users_proto_goTypes = nil
	file_user_v1_rpc_user_get_users_proto_depIdxs = nil
}
