// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/rpc/token/login_user.proto

package userv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_user_v1_rpc_token_login_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_rpc_token_login_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_rpc_token_login_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *Tokens                `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_user_v1_rpc_token_login_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_rpc_token_login_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_rpc_token_login_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginUserResponse) GetTokens() *Tokens {
	if x != nil {
		return x.Tokens
	}
	return nil
}

var File_user_v1_rpc_token_login_user_proto protoreflect.FileDescriptor

const file_user_v1_rpc_token_login_user_proto_rawDesc = "" +
	"\n" +
	"\"user/v1/rpc/token/login_user.proto\x12\auser.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1auser/v1/models/token.proto\"b\n" +
	"\x10LoginUserRequest\x12$\n" +
	"\x05email\x18\x01 \x01(\tB\x0e\xbaH\v\xc8\x01\x01r\x06\x10\x05\x18d`\x01R\x05email\x12(\n" +
	"\bpassword\x18\x03 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\b\x18dR\bpassword\"<\n" +
	"\x11LoginUserResponse\x12'\n" +
	"\x06tokens\x18\x01 \x01(\v2\x0f.user.v1.TokensR\x06tokensB\x14Z\x12api/user/v1;userv1b\x06proto3"

var (
	file_user_v1_rpc_token_login_user_proto_rawDescOnce sync.Once
	file_user_v1_rpc_token_login_user_proto_rawDescData []byte
)

func file_user_v1_rpc_token_login_user_proto_rawDescGZIP() []byte {
	file_user_v1_rpc_token_login_user_proto_rawDescOnce.Do(func() {
		file_user_v1_rpc_token_login_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_rpc_token_login_user_proto_rawDesc), len(file_user_v1_rpc_token_login_user_proto_rawDesc)))
	})
	return file_user_v1_rpc_token_login_user_proto_rawDescData
}

var file_user_v1_rpc_token_login_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_v1_rpc_token_login_user_proto_goTypes = []any{
	(*LoginUserRequest)(nil),  // 0: user.v1.LoginUserRequest
	(*LoginUserResponse)(nil), // 1: user.v1.LoginUserResponse
	(*Tokens)(nil),            // 2: user.v1.Tokens
}
var file_user_v1_rpc_token_login_user_proto_depIdxs = []int32{
	2, // 0: user.v1.LoginUserResponse.tokens:type_name -> user.v1.Tokens
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_v1_rpc_token_login_user_proto_init() }
func file_user_v1_rpc_token_login_user_proto_init() {
	if File_user_v1_rpc_token_login_user_proto != nil {
		return
	}
	file_user_v1_models_token_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_rpc_token_login_user_proto_rawDesc), len(file_user_v1_rpc_token_login_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_rpc_token_login_user_proto_goTypes,
		DependencyIndexes: file_user_v1_rpc_token_login_user_proto_depIdxs,
		MessageInfos:      file_user_v1_rpc_token_login_user_proto_msgTypes,
	}.Build()
	File_user_v1_rpc_token_login_user_proto = out.File
	file_user_v1_rpc_token_login_user_proto_goTypes = nil
	file_user_v1_rpc_token_login_user_proto_depIdxs = nil
}
