// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/models/token.proto

package userv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tokens struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Access        string                 `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	Refresh       string                 `protobuf:"bytes,2,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tokens) Reset() {
	*x = Tokens{}
	mi := &file_user_v1_models_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tokens) ProtoMessage() {}

func (x *Tokens) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_models_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tokens.ProtoReflect.Descriptor instead.
func (*Tokens) Descriptor() ([]byte, []int) {
	return file_user_v1_models_token_proto_rawDescGZIP(), []int{0}
}

func (x *Tokens) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *Tokens) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

var File_user_v1_models_token_proto protoreflect.FileDescriptor

const file_user_v1_models_token_proto_rawDesc = "" +
	"\n" +
	"\x1auser/v1/models/token.proto\x12\auser.v1\x1a\x1bbuf/validate/validate.proto\":\n" +
	"\x06Tokens\x12\x16\n" +
	"\x06access\x18\x01 \x01(\tR\x06access\x12\x18\n" +
	"\arefresh\x18\x02 \x01(\tR\arefreshB\x14Z\x12api/user/v1;userv1b\x06proto3"

var (
	file_user_v1_models_token_proto_rawDescOnce sync.Once
	file_user_v1_models_token_proto_rawDescData []byte
)

func file_user_v1_models_token_proto_rawDescGZIP() []byte {
	file_user_v1_models_token_proto_rawDescOnce.Do(func() {
		file_user_v1_models_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_models_token_proto_rawDesc), len(file_user_v1_models_token_proto_rawDesc)))
	})
	return file_user_v1_models_token_proto_rawDescData
}

var file_user_v1_models_token_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_v1_models_token_proto_goTypes = []any{
	(*Tokens)(nil), // 0: user.v1.Tokens
}
var file_user_v1_models_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_models_token_proto_init() }
func file_user_v1_models_token_proto_init() {
	if File_user_v1_models_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_models_token_proto_rawDesc), len(file_user_v1_models_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_models_token_proto_goTypes,
		DependencyIndexes: file_user_v1_models_token_proto_depIdxs,
		MessageInfos:      file_user_v1_models_token_proto_msgTypes,
	}.Build()
	File_user_v1_models_token_proto = out.File
	file_user_v1_models_token_proto_goTypes = nil
	file_user_v1_models_token_proto_depIdxs = nil
}
