// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/rpc/user/update_user_activity.proto

package userv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsActive      *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserActivityRequest) Reset() {
	*x = UpdateUserActivityRequest{}
	mi := &file_user_v1_rpc_user_update_user_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserActivityRequest) ProtoMessage() {}

func (x *UpdateUserActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_rpc_user_update_user_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserActivityRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserActivityRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_rpc_user_update_user_activity_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUserActivityRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserActivityRequest) GetIsActive() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsActive
	}
	return nil
}

type UpdateUserActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=isActive,proto3" json:"isActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserActivityResponse) Reset() {
	*x = UpdateUserActivityResponse{}
	mi := &file_user_v1_rpc_user_update_user_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserActivityResponse) ProtoMessage() {}

func (x *UpdateUserActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_rpc_user_update_user_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserActivityResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserActivityResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_rpc_user_update_user_activity_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserActivityResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_user_v1_rpc_user_update_user_activity_proto protoreflect.FileDescriptor

const file_user_v1_rpc_user_update_user_activity_proto_rawDesc = "" +
	"\n" +
	"+user/v1/rpc/user/update_user_activity.proto\x12\auser.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/wrappers.proto\"x\n" +
	"\x19UpdateUserActivityRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\x03B\n" +
	"\xbaH\a\xc8\x01\x01\"\x02(\x01R\x02id\x12?\n" +
	"\tis_active\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueB\x06\xbaH\x03\xc8\x01\x01R\bisActive\"8\n" +
	"\x1aUpdateUserActivityResponse\x12\x1a\n" +
	"\bisActive\x18\x01 \x01(\bR\bisActiveB\x14Z\x12api/user/v1;userv1b\x06proto3"

var (
	file_user_v1_rpc_user_update_user_activity_proto_rawDescOnce sync.Once
	file_user_v1_rpc_user_update_user_activity_proto_rawDescData []byte
)

func file_user_v1_rpc_user_update_user_activity_proto_rawDescGZIP() []byte {
	file_user_v1_rpc_user_update_user_activity_proto_rawDescOnce.Do(func() {
		file_user_v1_rpc_user_update_user_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_rpc_user_update_user_activity_proto_rawDesc), len(file_user_v1_rpc_user_update_user_activity_proto_rawDesc)))
	})
	return file_user_v1_rpc_user_update_user_activity_proto_rawDescData
}

var file_user_v1_rpc_user_update_user_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_v1_rpc_user_update_user_activity_proto_goTypes = []any{
	(*UpdateUserActivityRequest)(nil),  // 0: user.v1.UpdateUserActivityRequest
	(*UpdateUserActivityResponse)(nil), // 1: user.v1.UpdateUserActivityResponse
	(*wrapperspb.BoolValue)(nil),       // 2: google.protobuf.BoolValue
}
var file_user_v1_rpc_user_update_user_activity_proto_depIdxs = []int32{
	2, // 0: user.v1.UpdateUserActivityRequest.is_active:type_name -> google.protobuf.BoolValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_v1_rpc_user_update_user_activity_proto_init() }
func file_user_v1_rpc_user_update_user_activity_proto_init() {
	if File_user_v1_rpc_user_update_user_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_rpc_user_update_user_activity_proto_rawDesc), len(file_user_v1_rpc_user_update_user_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_rpc_user_update_user_activity_proto_goTypes,
		DependencyIndexes: file_user_v1_rpc_user_update_user_activity_proto_depIdxs,
		MessageInfos:      file_user_v1_rpc_user_update_user_activity_proto_msgTypes,
	}.Build()
	File_user_v1_rpc_user_update_user_activity_proto = out.File
	file_user_v1_rpc_user_update_user_activity_proto_goTypes = nil
	file_user_v1_rpc_user_update_user_activity_proto_depIdxs = nil
}
