// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/rpc/user/update_user.proto

package userv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_v1_rpc_user_update_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_rpc_user_update_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_rpc_user_update_user_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UpdateUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_user_v1_rpc_user_update_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_rpc_user_update_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_rpc_user_update_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserResponse) GetUser() *UpdateUser {
	if x != nil {
		return x.User
	}
	return nil
}

var File_user_v1_rpc_user_update_user_proto protoreflect.FileDescriptor

const file_user_v1_rpc_user_update_user_proto_rawDesc = "" +
	"\n" +
	"\"user/v1/rpc/user/update_user.proto\x12\auser.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19user/v1/models/user.proto\"\x7f\n" +
	"\x11UpdateUserRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\x03B\n" +
	"\xbaH\a\xc8\x01\x01\"\x02(\x01R\x02id\x12$\n" +
	"\x05email\x18\x02 \x01(\tB\x0e\xbaH\v\xc8\x01\x01r\x06\x10\x05\x18d`\x01R\x05email\x12(\n" +
	"\busername\x18\x03 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x01\x18dR\busername\"=\n" +
	"\x12UpdateUserResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.user.v1.UpdateUserR\x04userB\x14Z\x12api/user/v1;userv1b\x06proto3"

var (
	file_user_v1_rpc_user_update_user_proto_rawDescOnce sync.Once
	file_user_v1_rpc_user_update_user_proto_rawDescData []byte
)

func file_user_v1_rpc_user_update_user_proto_rawDescGZIP() []byte {
	file_user_v1_rpc_user_update_user_proto_rawDescOnce.Do(func() {
		file_user_v1_rpc_user_update_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_rpc_user_update_user_proto_rawDesc), len(file_user_v1_rpc_user_update_user_proto_rawDesc)))
	})
	return file_user_v1_rpc_user_update_user_proto_rawDescData
}

var file_user_v1_rpc_user_update_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_v1_rpc_user_update_user_proto_goTypes = []any{
	(*UpdateUserRequest)(nil),  // 0: user.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil), // 1: user.v1.UpdateUserResponse
	(*UpdateUser)(nil),         // 2: user.v1.UpdateUser
}
var file_user_v1_rpc_user_update_user_proto_depIdxs = []int32{
	2, // 0: user.v1.UpdateUserResponse.user:type_name -> user.v1.UpdateUser
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_v1_rpc_user_update_user_proto_init() }
func file_user_v1_rpc_user_update_user_proto_init() {
	if File_user_v1_rpc_user_update_user_proto != nil {
		return
	}
	file_user_v1_models_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_rpc_user_update_user_proto_rawDesc), len(file_user_v1_rpc_user_update_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_rpc_user_update_user_proto_goTypes,
		DependencyIndexes: file_user_v1_rpc_user_update_user_proto_depIdxs,
		MessageInfos:      file_user_v1_rpc_user_update_user_proto_msgTypes,
	}.Build()
	File_user_v1_rpc_user_update_user_proto = out.File
	file_user_v1_rpc_user_update_user_proto_goTypes = nil
	file_user_v1_rpc_user_update_user_proto_depIdxs = nil
}
