// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/enums/user_role.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	UserRole_USER_ROLE_USER        UserRole = 1
	UserRole_USER_ROLE_MODERATOR   UserRole = 2
	UserRole_USER_ROLE_ADMIN       UserRole = 3
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_USER",
		2: "USER_ROLE_MODERATOR",
		3: "USER_ROLE_ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_USER":        1,
		"USER_ROLE_MODERATOR":   2,
		"USER_ROLE_ADMIN":       3,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_enums_user_role_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_user_v1_enums_user_role_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_enums_user_role_proto_rawDescGZIP(), []int{0}
}

var File_user_v1_enums_user_role_proto protoreflect.FileDescriptor

const file_user_v1_enums_user_role_proto_rawDesc = "" +
	"\n" +
	"\x1duser/v1/enums/user_role.proto\x12\auser.v1*g\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_ROLE_USER\x10\x01\x12\x17\n" +
	"\x13USER_ROLE_MODERATOR\x10\x02\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x03B\x14Z\x12api/user/v1;userv1b\x06proto3"

var (
	file_user_v1_enums_user_role_proto_rawDescOnce sync.Once
	file_user_v1_enums_user_role_proto_rawDescData []byte
)

func file_user_v1_enums_user_role_proto_rawDescGZIP() []byte {
	file_user_v1_enums_user_role_proto_rawDescOnce.Do(func() {
		file_user_v1_enums_user_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_enums_user_role_proto_rawDesc), len(file_user_v1_enums_user_role_proto_rawDesc)))
	})
	return file_user_v1_enums_user_role_proto_rawDescData
}

var file_user_v1_enums_user_role_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_v1_enums_user_role_proto_goTypes = []any{
	(UserRole)(0), // 0: user.v1.UserRole
}
var file_user_v1_enums_user_role_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_enums_user_role_proto_init() }
func file_user_v1_enums_user_role_proto_init() {
	if File_user_v1_enums_user_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_enums_user_role_proto_rawDesc), len(file_user_v1_enums_user_role_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_enums_user_role_proto_goTypes,
		DependencyIndexes: file_user_v1_enums_user_role_proto_depIdxs,
		EnumInfos:         file_user_v1_enums_user_role_proto_enumTypes,
	}.Build()
	File_user_v1_enums_user_role_proto = out.File
	file_user_v1_enums_user_role_proto_goTypes = nil
	file_user_v1_enums_user_role_proto_depIdxs = nil
}
