// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/models/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      *string                `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Role          UserRole               `protobuf:"varint,4,opt,name=role,proto3,enum=user.v1.UserRole" json:"role,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_v1_models_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_models_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_v1_models_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *User) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UserShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      *string                `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Role          UserRole               `protobuf:"varint,4,opt,name=role,proto3,enum=user.v1.UserRole" json:"role,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserShort) Reset() {
	*x = UserShort{}
	mi := &file_user_v1_models_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserShort) ProtoMessage() {}

func (x *UserShort) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_models_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserShort.ProtoReflect.Descriptor instead.
func (*UserShort) Descriptor() ([]byte, []int) {
	return file_user_v1_models_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserShort) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserShort) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserShort) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UserShort) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

func (x *UserShort) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUser) Reset() {
	*x = UpdateUser{}
	mi := &file_user_v1_models_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUser) ProtoMessage() {}

func (x *UpdateUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_models_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUser.ProtoReflect.Descriptor instead.
func (*UpdateUser) Descriptor() ([]byte, []int) {
	return file_user_v1_models_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdateHotelTitle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	HotelSlug     string                 `protobuf:"bytes,2,opt,name=hotel_slug,json=hotelSlug,proto3" json:"hotel_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHotelTitle) Reset() {
	*x = UpdateHotelTitle{}
	mi := &file_user_v1_models_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHotelTitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHotelTitle) ProtoMessage() {}

func (x *UpdateHotelTitle) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_models_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHotelTitle.ProtoReflect.Descriptor instead.
func (*UpdateHotelTitle) Descriptor() ([]byte, []int) {
	return file_user_v1_models_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateHotelTitle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateHotelTitle) GetHotelSlug() string {
	if x != nil {
		return x.HotelSlug
	}
	return ""
}

var File_user_v1_models_user_proto protoreflect.FileDescriptor

const file_user_v1_models_user_proto_rawDesc = "" +
	"\n" +
	"\x19user/v1/models/user.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1duser/v1/enums/user_role.proto\"\x94\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x00R\busername\x88\x01\x01\x12%\n" +
	"\x04role\x18\x04 \x01(\x0e2\x11.user.v1.UserRoleR\x04role\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\v\n" +
	"\t_username\"\xa3\x01\n" +
	"\tUserShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x00R\busername\x88\x01\x01\x12%\n" +
	"\x04role\x18\x04 \x01(\x0e2\x11.user.v1.UserRoleR\x04role\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActiveB\v\n" +
	"\t_username\">\n" +
	"\n" +
	"UpdateUser\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"G\n" +
	"\x10UpdateHotelTitle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"hotel_slug\x18\x02 \x01(\tR\thotelSlugB\x14Z\x12api/user/v1;userv1b\x06proto3"

var (
	file_user_v1_models_user_proto_rawDescOnce sync.Once
	file_user_v1_models_user_proto_rawDescData []byte
)

func file_user_v1_models_user_proto_rawDescGZIP() []byte {
	file_user_v1_models_user_proto_rawDescOnce.Do(func() {
		file_user_v1_models_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_models_user_proto_rawDesc), len(file_user_v1_models_user_proto_rawDesc)))
	})
	return file_user_v1_models_user_proto_rawDescData
}

var file_user_v1_models_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_v1_models_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: user.v1.User
	(*UserShort)(nil),             // 1: user.v1.UserShort
	(*UpdateUser)(nil),            // 2: user.v1.UpdateUser
	(*UpdateHotelTitle)(nil),      // 3: user.v1.UpdateHotelTitle
	(UserRole)(0),                 // 4: user.v1.UserRole
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_user_v1_models_user_proto_depIdxs = []int32{
	4, // 0: user.v1.User.role:type_name -> user.v1.UserRole
	5, // 1: user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: user.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	4, // 3: user.v1.UserShort.role:type_name -> user.v1.UserRole
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_user_v1_models_user_proto_init() }
func file_user_v1_models_user_proto_init() {
	if File_user_v1_models_user_proto != nil {
		return
	}
	file_user_v1_enums_user_role_proto_init()
	file_user_v1_models_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_user_v1_models_user_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_models_user_proto_rawDesc), len(file_user_v1_models_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_models_user_proto_goTypes,
		DependencyIndexes: file_user_v1_models_user_proto_depIdxs,
		MessageInfos:      file_user_v1_models_user_proto_msgTypes,
	}.Build()
	File_user_v1_models_user_proto = out.File
	file_user_v1_models_user_proto_goTypes = nil
	file_user_v1_models_user_proto_depIdxs = nil
}
