// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hotel/v1/rpc/room/create_room_by_hotel_id.proto

package hotelv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoomByHotelIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelId       string                 `protobuf:"bytes,1,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,4,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Type          RoomType               `protobuf:"varint,5,opt,name=type,proto3,enum=hotel.v1.RoomType" json:"type,omitempty"`
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	Capacity      int32                  `protobuf:"varint,7,opt,name=capacity,proto3" json:"capacity,omitempty"`
	AreaSqm       float64                `protobuf:"fixed64,8,opt,name=area_sqm,json=areaSqm,proto3" json:"area_sqm,omitempty"`
	Floor         int32                  `protobuf:"varint,9,opt,name=floor,proto3" json:"floor,omitempty"`
	Amenities     []string               `protobuf:"bytes,10,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Images        []string               `protobuf:"bytes,11,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomByHotelIDRequest) Reset() {
	*x = CreateRoomByHotelIDRequest{}
	mi := &file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomByHotelIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomByHotelIDRequest) ProtoMessage() {}

func (x *CreateRoomByHotelIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomByHotelIDRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomByHotelIDRequest) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomByHotelIDRequest) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *CreateRoomByHotelIDRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRoomByHotelIDRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateRoomByHotelIDRequest) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *CreateRoomByHotelIDRequest) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *CreateRoomByHotelIDRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateRoomByHotelIDRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreateRoomByHotelIDRequest) GetAreaSqm() float64 {
	if x != nil {
		return x.AreaSqm
	}
	return 0
}

func (x *CreateRoomByHotelIDRequest) GetFloor() int32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *CreateRoomByHotelIDRequest) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *CreateRoomByHotelIDRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type CreateRoomByHotelIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomByHotelIDResponse) Reset() {
	*x = CreateRoomByHotelIDResponse{}
	mi := &file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomByHotelIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomByHotelIDResponse) ProtoMessage() {}

func (x *CreateRoomByHotelIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomByHotelIDResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomByHotelIDResponse) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomByHotelIDResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

var File_hotel_v1_rpc_room_create_room_by_hotel_id_proto protoreflect.FileDescriptor

const file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_rawDesc = "" +
	"\n" +
	"/hotel/v1/rpc/room/create_room_by_hotel_id.proto\x12\bhotel.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1ehotel/v1/enums/room_type.proto\x1a\x1ahotel/v1/models/room.proto\"\xa8\x03\n" +
	"\x1aCreateRoomByHotelIDRequest\x12#\n" +
	"\bhotel_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\ahotelId\x12\x1c\n" +
	"\x05title\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12'\n" +
	"\vroom_number\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"roomNumber\x12.\n" +
	"\x04type\x18\x05 \x01(\x0e2\x12.hotel.v1.RoomTypeB\x06\xbaH\x03\xc8\x01\x01R\x04type\x12\x1c\n" +
	"\x05price\x18\x06 \x01(\x02B\x06\xbaH\x03\xc8\x01\x01R\x05price\x12\"\n" +
	"\bcapacity\x18\a \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\bcapacity\x12!\n" +
	"\barea_sqm\x18\b \x01(\x01B\x06\xbaH\x03\xc8\x01\x01R\aareaSqm\x12\x1c\n" +
	"\x05floor\x18\t \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\x05floor\x12\x1c\n" +
	"\tamenities\x18\n" +
	" \x03(\tR\tamenities\x12\x16\n" +
	"\x06images\x18\v \x03(\tR\x06imagesB\x0e\n" +
	"\f_description\"A\n" +
	"\x1bCreateRoomByHotelIDResponse\x12\"\n" +
	"\x04room\x18\x01 \x01(\v2\x0e.hotel.v1.RoomR\x04roomB\x16Z\x14api/hotel/v1;hotelv1b\x06proto3"

var (
	file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_rawDescOnce sync.Once
	file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_rawDescData []byte
)

func file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_rawDescGZIP() []byte {
	file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_rawDescOnce.Do(func() {
		file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_rawDesc), len(file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_rawDesc)))
	})
	return file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_rawDescData
}

var file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_goTypes = []any{
	(*CreateRoomByHotelIDRequest)(nil),  // 0: hotel.v1.CreateRoomByHotelIDRequest
	(*CreateRoomByHotelIDResponse)(nil), // 1: hotel.v1.CreateRoomByHotelIDResponse
	(RoomType)(0),                       // 2: hotel.v1.RoomType
	(*Room)(nil),                        // 3: hotel.v1.Room
}
var file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_depIdxs = []int32{
	2, // 0: hotel.v1.CreateRoomByHotelIDRequest.type:type_name -> hotel.v1.RoomType
	3, // 1: hotel.v1.CreateRoomByHotelIDResponse.room:type_name -> hotel.v1.Room
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_init() }
func file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_init() {
	if File_hotel_v1_rpc_room_create_room_by_hotel_id_proto != nil {
		return
	}
	file_hotel_v1_enums_room_type_proto_init()
	file_hotel_v1_models_room_proto_init()
	file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_rawDesc), len(file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_goTypes,
		DependencyIndexes: file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_depIdxs,
		MessageInfos:      file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_msgTypes,
	}.Build()
	File_hotel_v1_rpc_room_create_room_by_hotel_id_proto = out.File
	file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_goTypes = nil
	file_hotel_v1_rpc_room_create_room_by_hotel_id_proto_depIdxs = nil
}
