// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hotel/v1/rpc/room/create_room.proto

package hotelv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CitySlug      string                 `protobuf:"bytes,2,opt,name=city_slug,json=citySlug,proto3" json:"city_slug,omitempty"`
	HotelSlug     string                 `protobuf:"bytes,3,opt,name=hotel_slug,json=hotelSlug,proto3" json:"hotel_slug,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,6,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Type          RoomType               `protobuf:"varint,7,opt,name=type,proto3,enum=hotel.v1.RoomType" json:"type,omitempty"`
	Price         float32                `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	Capacity      int64                  `protobuf:"varint,9,opt,name=capacity,proto3" json:"capacity,omitempty"`
	AreaSqm       float32                `protobuf:"fixed32,10,opt,name=area_sqm,json=areaSqm,proto3" json:"area_sqm,omitempty"`
	Floor         int64                  `protobuf:"varint,11,opt,name=floor,proto3" json:"floor,omitempty"`
	Amenities     []string               `protobuf:"bytes,12,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Images        []string               `protobuf:"bytes,13,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_hotel_v1_rpc_room_create_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_room_create_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_room_create_room_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *CreateRoomRequest) GetCitySlug() string {
	if x != nil {
		return x.CitySlug
	}
	return ""
}

func (x *CreateRoomRequest) GetHotelSlug() string {
	if x != nil {
		return x.HotelSlug
	}
	return ""
}

func (x *CreateRoomRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRoomRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateRoomRequest) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *CreateRoomRequest) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *CreateRoomRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateRoomRequest) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreateRoomRequest) GetAreaSqm() float32 {
	if x != nil {
		return x.AreaSqm
	}
	return 0
}

func (x *CreateRoomRequest) GetFloor() int64 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *CreateRoomRequest) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *CreateRoomRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_hotel_v1_rpc_room_create_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_room_create_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_room_create_room_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

var File_hotel_v1_rpc_room_create_room_proto protoreflect.FileDescriptor

const file_hotel_v1_rpc_room_create_room_proto_rawDesc = "" +
	"\n" +
	"#hotel/v1/rpc/room/create_room.proto\x12\bhotel.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1ehotel/v1/enums/room_type.proto\x1a\x1ahotel/v1/models/room.proto\"\xae\x04\n" +
	"\x11CreateRoomRequest\x124\n" +
	"\fcountry_code\x18\x01 \x01(\tB\x11\xbaH\x0er\f2\n" +
	"^[a-z]{2}$R\vcountryCode\x12<\n" +
	"\tcity_slug\x18\x02 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\bcitySlug\x12>\n" +
	"\n" +
	"hotel_slug\x18\x03 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\thotelSlug\x12\x1c\n" +
	"\x05title\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05title\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x12'\n" +
	"\vroom_number\x18\x06 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"roomNumber\x12.\n" +
	"\x04type\x18\a \x01(\x0e2\x12.hotel.v1.RoomTypeB\x06\xbaH\x03\xc8\x01\x01R\x04type\x12\x1c\n" +
	"\x05price\x18\b \x01(\x02B\x06\xbaH\x03\xc8\x01\x01R\x05price\x12\"\n" +
	"\bcapacity\x18\t \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\bcapacity\x12!\n" +
	"\barea_sqm\x18\n" +
	" \x01(\x02B\x06\xbaH\x03\xc8\x01\x01R\aareaSqm\x12\x1c\n" +
	"\x05floor\x18\v \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\x05floor\x12\x1c\n" +
	"\tamenities\x18\f \x03(\tR\tamenities\x12\x16\n" +
	"\x06images\x18\r \x03(\tR\x06imagesB\x0e\n" +
	"\f_description\"8\n" +
	"\x12CreateRoomResponse\x12\"\n" +
	"\x04room\x18\x01 \x01(\v2\x0e.hotel.v1.RoomR\x04roomB\x16Z\x14api/hotel/v1;hotelv1b\x06proto3"

var (
	file_hotel_v1_rpc_room_create_room_proto_rawDescOnce sync.Once
	file_hotel_v1_rpc_room_create_room_proto_rawDescData []byte
)

func file_hotel_v1_rpc_room_create_room_proto_rawDescGZIP() []byte {
	file_hotel_v1_rpc_room_create_room_proto_rawDescOnce.Do(func() {
		file_hotel_v1_rpc_room_create_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_room_create_room_proto_rawDesc), len(file_hotel_v1_rpc_room_create_room_proto_rawDesc)))
	})
	return file_hotel_v1_rpc_room_create_room_proto_rawDescData
}

var file_hotel_v1_rpc_room_create_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hotel_v1_rpc_room_create_room_proto_goTypes = []any{
	(*CreateRoomRequest)(nil),  // 0: hotel.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil), // 1: hotel.v1.CreateRoomResponse
	(RoomType)(0),              // 2: hotel.v1.RoomType
	(*Room)(nil),               // 3: hotel.v1.Room
}
var file_hotel_v1_rpc_room_create_room_proto_depIdxs = []int32{
	2, // 0: hotel.v1.CreateRoomRequest.type:type_name -> hotel.v1.RoomType
	3, // 1: hotel.v1.CreateRoomResponse.room:type_name -> hotel.v1.Room
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hotel_v1_rpc_room_create_room_proto_init() }
func file_hotel_v1_rpc_room_create_room_proto_init() {
	if File_hotel_v1_rpc_room_create_room_proto != nil {
		return
	}
	file_hotel_v1_enums_room_type_proto_init()
	file_hotel_v1_models_room_proto_init()
	file_hotel_v1_rpc_room_create_room_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_room_create_room_proto_rawDesc), len(file_hotel_v1_rpc_room_create_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotel_v1_rpc_room_create_room_proto_goTypes,
		DependencyIndexes: file_hotel_v1_rpc_room_create_room_proto_depIdxs,
		MessageInfos:      file_hotel_v1_rpc_room_create_room_proto_msgTypes,
	}.Build()
	File_hotel_v1_rpc_room_create_room_proto = out.File
	file_hotel_v1_rpc_room_create_room_proto_goTypes = nil
	file_hotel_v1_rpc_room_create_room_proto_depIdxs = nil
}
