// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hotel/v1/rpc/hotel/create_hotel.proto

package hotelv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHotelLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float32                `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHotelLocationRequest) Reset() {
	*x = CreateHotelLocationRequest{}
	mi := &file_hotel_v1_rpc_hotel_create_hotel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHotelLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHotelLocationRequest) ProtoMessage() {}

func (x *CreateHotelLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_hotel_create_hotel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHotelLocationRequest.ProtoReflect.Descriptor instead.
func (*CreateHotelLocationRequest) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_hotel_create_hotel_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHotelLocationRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateHotelLocationRequest) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type CreateHotelRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	CountryCode   string                      `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CitySlug      string                      `protobuf:"bytes,2,opt,name=city_slug,json=citySlug,proto3" json:"city_slug,omitempty"`
	Title         string                      `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	OwnerId       int64                       `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Description   *string                     `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Address       string                      `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Location      *CreateHotelLocationRequest `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHotelRequest) Reset() {
	*x = CreateHotelRequest{}
	mi := &file_hotel_v1_rpc_hotel_create_hotel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHotelRequest) ProtoMessage() {}

func (x *CreateHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_hotel_create_hotel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHotelRequest.ProtoReflect.Descriptor instead.
func (*CreateHotelRequest) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_hotel_create_hotel_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHotelRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *CreateHotelRequest) GetCitySlug() string {
	if x != nil {
		return x.CitySlug
	}
	return ""
}

func (x *CreateHotelRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateHotelRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateHotelRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateHotelRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateHotelRequest) GetLocation() *CreateHotelLocationRequest {
	if x != nil {
		return x.Location
	}
	return nil
}

type CreateHotelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hotel         *CreateHotel           `protobuf:"bytes,1,opt,name=hotel,proto3" json:"hotel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHotelResponse) Reset() {
	*x = CreateHotelResponse{}
	mi := &file_hotel_v1_rpc_hotel_create_hotel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHotelResponse) ProtoMessage() {}

func (x *CreateHotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_hotel_create_hotel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHotelResponse.ProtoReflect.Descriptor instead.
func (*CreateHotelResponse) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_hotel_create_hotel_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHotelResponse) GetHotel() *CreateHotel {
	if x != nil {
		return x.Hotel
	}
	return nil
}

var File_hotel_v1_rpc_hotel_create_hotel_proto protoreflect.FileDescriptor

const file_hotel_v1_rpc_hotel_create_hotel_proto_rawDesc = "" +
	"\n" +
	"%hotel/v1/rpc/hotel/create_hotel.proto\x12\bhotel.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bhotel/v1/models/hotel.proto\"x\n" +
	"\x1aCreateHotelLocationRequest\x12+\n" +
	"\blatitude\x18\x01 \x01(\x02B\x0f\xbaH\f\n" +
	"\n" +
	"\x1d\x00\x00\xb4B-\x00\x00\xb4\xc2R\blatitude\x12-\n" +
	"\tlongitude\x18\x02 \x01(\x02B\x0f\xbaH\f\n" +
	"\n" +
	"\x1d\x00\x004C-\x00\x004\xc3R\tlongitude\"\xec\x02\n" +
	"\x12CreateHotelRequest\x124\n" +
	"\fcountry_code\x18\x01 \x01(\tB\x11\xbaH\x0er\f2\n" +
	"^[a-z]{2}$R\vcountryCode\x12<\n" +
	"\tcity_slug\x18\x02 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\bcitySlug\x12\x1c\n" +
	"\x05title\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05title\x12!\n" +
	"\bowner_id\x18\x04 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\aownerId\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x12 \n" +
	"\aaddress\x18\x06 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aaddress\x12H\n" +
	"\blocation\x18\a \x01(\v2$.hotel.v1.CreateHotelLocationRequestB\x06\xbaH\x03\xc8\x01\x01R\blocationB\x0e\n" +
	"\f_description\"B\n" +
	"\x13CreateHotelResponse\x12+\n" +
	"\x05hotel\x18\x01 \x01(\v2\x15.hotel.v1.CreateHotelR\x05hotelB\x16Z\x14api/hotel/v1;hotelv1b\x06proto3"

var (
	file_hotel_v1_rpc_hotel_create_hotel_proto_rawDescOnce sync.Once
	file_hotel_v1_rpc_hotel_create_hotel_proto_rawDescData []byte
)

func file_hotel_v1_rpc_hotel_create_hotel_proto_rawDescGZIP() []byte {
	file_hotel_v1_rpc_hotel_create_hotel_proto_rawDescOnce.Do(func() {
		file_hotel_v1_rpc_hotel_create_hotel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_hotel_create_hotel_proto_rawDesc), len(file_hotel_v1_rpc_hotel_create_hotel_proto_rawDesc)))
	})
	return file_hotel_v1_rpc_hotel_create_hotel_proto_rawDescData
}

var file_hotel_v1_rpc_hotel_create_hotel_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hotel_v1_rpc_hotel_create_hotel_proto_goTypes = []any{
	(*CreateHotelLocationRequest)(nil), // 0: hotel.v1.CreateHotelLocationRequest
	(*CreateHotelRequest)(nil),         // 1: hotel.v1.CreateHotelRequest
	(*CreateHotelResponse)(nil),        // 2: hotel.v1.CreateHotelResponse
	(*CreateHotel)(nil),                // 3: hotel.v1.CreateHotel
}
var file_hotel_v1_rpc_hotel_create_hotel_proto_depIdxs = []int32{
	0, // 0: hotel.v1.CreateHotelRequest.location:type_name -> hotel.v1.CreateHotelLocationRequest
	3, // 1: hotel.v1.CreateHotelResponse.hotel:type_name -> hotel.v1.CreateHotel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hotel_v1_rpc_hotel_create_hotel_proto_init() }
func file_hotel_v1_rpc_hotel_create_hotel_proto_init() {
	if File_hotel_v1_rpc_hotel_create_hotel_proto != nil {
		return
	}
	file_hotel_v1_models_hotel_proto_init()
	file_hotel_v1_rpc_hotel_create_hotel_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_hotel_create_hotel_proto_rawDesc), len(file_hotel_v1_rpc_hotel_create_hotel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotel_v1_rpc_hotel_create_hotel_proto_goTypes,
		DependencyIndexes: file_hotel_v1_rpc_hotel_create_hotel_proto_depIdxs,
		MessageInfos:      file_hotel_v1_rpc_hotel_create_hotel_proto_msgTypes,
	}.Build()
	File_hotel_v1_rpc_hotel_create_hotel_proto = out.File
	file_hotel_v1_rpc_hotel_create_hotel_proto_goTypes = nil
	file_hotel_v1_rpc_hotel_create_hotel_proto_depIdxs = nil
}
