// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hotel/v1/rpc/room/delete_room.proto

package hotelv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomRequest) Reset() {
	*x = DeleteRoomRequest{}
	mi := &file_hotel_v1_rpc_room_delete_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomRequest) ProtoMessage() {}

func (x *DeleteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_room_delete_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_room_delete_room_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomResponse) Reset() {
	*x = DeleteRoomResponse{}
	mi := &file_hotel_v1_rpc_room_delete_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomResponse) ProtoMessage() {}

func (x *DeleteRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_room_delete_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoomResponse) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_room_delete_room_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hotel_v1_rpc_room_delete_room_proto protoreflect.FileDescriptor

const file_hotel_v1_rpc_room_delete_room_proto_rawDesc = "" +
	"\n" +
	"#hotel/v1/rpc/room/delete_room.proto\x12\bhotel.v1\x1a\x1bbuf/validate/validate.proto\"-\n" +
	"\x11DeleteRoomRequest\x12\x18\n" +
	"\x02id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\".\n" +
	"\x12DeleteRoomResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\x16Z\x14api/hotel/v1;hotelv1b\x06proto3"

var (
	file_hotel_v1_rpc_room_delete_room_proto_rawDescOnce sync.Once
	file_hotel_v1_rpc_room_delete_room_proto_rawDescData []byte
)

func file_hotel_v1_rpc_room_delete_room_proto_rawDescGZIP() []byte {
	file_hotel_v1_rpc_room_delete_room_proto_rawDescOnce.Do(func() {
		file_hotel_v1_rpc_room_delete_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_room_delete_room_proto_rawDesc), len(file_hotel_v1_rpc_room_delete_room_proto_rawDesc)))
	})
	return file_hotel_v1_rpc_room_delete_room_proto_rawDescData
}

var file_hotel_v1_rpc_room_delete_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hotel_v1_rpc_room_delete_room_proto_goTypes = []any{
	(*DeleteRoomRequest)(nil),  // 0: hotel.v1.DeleteRoomRequest
	(*DeleteRoomResponse)(nil), // 1: hotel.v1.DeleteRoomResponse
}
var file_hotel_v1_rpc_room_delete_room_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hotel_v1_rpc_room_delete_room_proto_init() }
func file_hotel_v1_rpc_room_delete_room_proto_init() {
	if File_hotel_v1_rpc_room_delete_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_room_delete_room_proto_rawDesc), len(file_hotel_v1_rpc_room_delete_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotel_v1_rpc_room_delete_room_proto_goTypes,
		DependencyIndexes: file_hotel_v1_rpc_room_delete_room_proto_depIdxs,
		MessageInfos:      file_hotel_v1_rpc_room_delete_room_proto_msgTypes,
	}.Build()
	File_hotel_v1_rpc_room_delete_room_proto = out.File
	file_hotel_v1_rpc_room_delete_room_proto_goTypes = nil
	file_hotel_v1_rpc_room_delete_room_proto_depIdxs = nil
}
