// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hotel/v1/rpc/hotel/delete_hotel.proto

package hotelv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteHotelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CitySlug      string                 `protobuf:"bytes,2,opt,name=city_slug,json=citySlug,proto3" json:"city_slug,omitempty"`
	HotelSlug     string                 `protobuf:"bytes,3,opt,name=hotel_slug,json=hotelSlug,proto3" json:"hotel_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHotelRequest) Reset() {
	*x = DeleteHotelRequest{}
	mi := &file_hotel_v1_rpc_hotel_delete_hotel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHotelRequest) ProtoMessage() {}

func (x *DeleteHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_hotel_delete_hotel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHotelRequest.ProtoReflect.Descriptor instead.
func (*DeleteHotelRequest) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_hotel_delete_hotel_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteHotelRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *DeleteHotelRequest) GetCitySlug() string {
	if x != nil {
		return x.CitySlug
	}
	return ""
}

func (x *DeleteHotelRequest) GetHotelSlug() string {
	if x != nil {
		return x.HotelSlug
	}
	return ""
}

type DeleteHotelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHotelResponse) Reset() {
	*x = DeleteHotelResponse{}
	mi := &file_hotel_v1_rpc_hotel_delete_hotel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHotelResponse) ProtoMessage() {}

func (x *DeleteHotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_hotel_delete_hotel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHotelResponse.ProtoReflect.Descriptor instead.
func (*DeleteHotelResponse) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_hotel_delete_hotel_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteHotelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hotel_v1_rpc_hotel_delete_hotel_proto protoreflect.FileDescriptor

const file_hotel_v1_rpc_hotel_delete_hotel_proto_rawDesc = "" +
	"\n" +
	"%hotel/v1/rpc/hotel/delete_hotel.proto\x12\bhotel.v1\x1a\x1bbuf/validate/validate.proto\"\xc8\x01\n" +
	"\x12DeleteHotelRequest\x124\n" +
	"\fcountry_code\x18\x01 \x01(\tB\x11\xbaH\x0er\f2\n" +
	"^[a-z]{2}$R\vcountryCode\x12<\n" +
	"\tcity_slug\x18\x02 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\bcitySlug\x12>\n" +
	"\n" +
	"hotel_slug\x18\x03 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\thotelSlug\"/\n" +
	"\x13DeleteHotelResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\x16Z\x14api/hotel/v1;hotelv1b\x06proto3"

var (
	file_hotel_v1_rpc_hotel_delete_hotel_proto_rawDescOnce sync.Once
	file_hotel_v1_rpc_hotel_delete_hotel_proto_rawDescData []byte
)

func file_hotel_v1_rpc_hotel_delete_hotel_proto_rawDescGZIP() []byte {
	file_hotel_v1_rpc_hotel_delete_hotel_proto_rawDescOnce.Do(func() {
		file_hotel_v1_rpc_hotel_delete_hotel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_hotel_delete_hotel_proto_rawDesc), len(file_hotel_v1_rpc_hotel_delete_hotel_proto_rawDesc)))
	})
	return file_hotel_v1_rpc_hotel_delete_hotel_proto_rawDescData
}

var file_hotel_v1_rpc_hotel_delete_hotel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hotel_v1_rpc_hotel_delete_hotel_proto_goTypes = []any{
	(*DeleteHotelRequest)(nil),  // 0: hotel.v1.DeleteHotelRequest
	(*DeleteHotelResponse)(nil), // 1: hotel.v1.DeleteHotelResponse
}
var file_hotel_v1_rpc_hotel_delete_hotel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hotel_v1_rpc_hotel_delete_hotel_proto_init() }
func file_hotel_v1_rpc_hotel_delete_hotel_proto_init() {
	if File_hotel_v1_rpc_hotel_delete_hotel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_hotel_delete_hotel_proto_rawDesc), len(file_hotel_v1_rpc_hotel_delete_hotel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotel_v1_rpc_hotel_delete_hotel_proto_goTypes,
		DependencyIndexes: file_hotel_v1_rpc_hotel_delete_hotel_proto_depIdxs,
		MessageInfos:      file_hotel_v1_rpc_hotel_delete_hotel_proto_msgTypes,
	}.Build()
	File_hotel_v1_rpc_hotel_delete_hotel_proto = out.File
	file_hotel_v1_rpc_hotel_delete_hotel_proto_goTypes = nil
	file_hotel_v1_rpc_hotel_delete_hotel_proto_depIdxs = nil
}
