// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hotel/v1/rpc/room/get_rooms.proto

package hotelv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CitySlug      string                 `protobuf:"bytes,2,opt,name=city_slug,json=citySlug,proto3" json:"city_slug,omitempty"`
	HotelSlug     string                 `protobuf:"bytes,3,opt,name=hotel_slug,json=hotelSlug,proto3" json:"hotel_slug,omitempty"`
	Page          uint64                 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint64                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomsRequest) Reset() {
	*x = GetRoomsRequest{}
	mi := &file_hotel_v1_rpc_room_get_rooms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsRequest) ProtoMessage() {}

func (x *GetRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_room_get_rooms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetRoomsRequest) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_room_get_rooms_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoomsRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GetRoomsRequest) GetCitySlug() string {
	if x != nil {
		return x.CitySlug
	}
	return ""
}

func (x *GetRoomsRequest) GetHotelSlug() string {
	if x != nil {
		return x.HotelSlug
	}
	return ""
}

func (x *GetRoomsRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRoomsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomShort           `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint64                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomsResponse) Reset() {
	*x = GetRoomsResponse{}
	mi := &file_hotel_v1_rpc_room_get_rooms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsResponse) ProtoMessage() {}

func (x *GetRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_room_get_rooms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomsResponse) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_room_get_rooms_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoomsResponse) GetRooms() []*RoomShort {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *GetRoomsResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetRoomsResponse) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRoomsResponse) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_hotel_v1_rpc_room_get_rooms_proto protoreflect.FileDescriptor

const file_hotel_v1_rpc_room_get_rooms_proto_rawDesc = "" +
	"\n" +
	"!hotel/v1/rpc/room/get_rooms.proto\x12\bhotel.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1ahotel/v1/models/room.proto\"\x83\x02\n" +
	"\x0fGetRoomsRequest\x124\n" +
	"\fcountry_code\x18\x01 \x01(\tB\x11\xbaH\x0er\f2\n" +
	"^[a-z]{2}$R\vcountryCode\x12<\n" +
	"\tcity_slug\x18\x02 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\bcitySlug\x12>\n" +
	"\n" +
	"hotel_slug\x18\x03 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\thotelSlug\x12\x1b\n" +
	"\x04page\x18\x04 \x01(\x04B\a\xbaH\x042\x02(\x01R\x04page\x12\x1f\n" +
	"\x05limit\x18\x05 \x01(\x04B\t\xbaH\x062\x04\x18d(\x01R\x05limit\"\x88\x01\n" +
	"\x10GetRoomsResponse\x12)\n" +
	"\x05rooms\x18\x01 \x03(\v2\x13.hotel.v1.RoomShortR\x05rooms\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x04R\x05limitB\x16Z\x14api/hotel/v1;hotelv1b\x06proto3"

var (
	file_hotel_v1_rpc_room_get_rooms_proto_rawDescOnce sync.Once
	file_hotel_v1_rpc_room_get_rooms_proto_rawDescData []byte
)

func file_hotel_v1_rpc_room_get_rooms_proto_rawDescGZIP() []byte {
	file_hotel_v1_rpc_room_get_rooms_proto_rawDescOnce.Do(func() {
		file_hotel_v1_rpc_room_get_rooms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_room_get_rooms_proto_rawDesc), len(file_hotel_v1_rpc_room_get_rooms_proto_rawDesc)))
	})
	return file_hotel_v1_rpc_room_get_rooms_proto_rawDescData
}

var file_hotel_v1_rpc_room_get_rooms_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hotel_v1_rpc_room_get_rooms_proto_goTypes = []any{
	(*GetRoomsRequest)(nil),  // 0: hotel.v1.GetRoomsRequest
	(*GetRoomsResponse)(nil), // 1: hotel.v1.GetRoomsResponse
	(*RoomShort)(nil),        // 2: hotel.v1.RoomShort
}
var file_hotel_v1_rpc_room_get_rooms_proto_depIdxs = []int32{
	2, // 0: hotel.v1.GetRoomsResponse.rooms:type_name -> hotel.v1.RoomShort
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hotel_v1_rpc_room_get_rooms_proto_init() }
func file_hotel_v1_rpc_room_get_rooms_proto_init() {
	if File_hotel_v1_rpc_room_get_rooms_proto != nil {
		return
	}
	file_hotel_v1_models_room_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_room_get_rooms_proto_rawDesc), len(file_hotel_v1_rpc_room_get_rooms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotel_v1_rpc_room_get_rooms_proto_goTypes,
		DependencyIndexes: file_hotel_v1_rpc_room_get_rooms_proto_depIdxs,
		MessageInfos:      file_hotel_v1_rpc_room_get_rooms_proto_msgTypes,
	}.Build()
	File_hotel_v1_rpc_room_get_rooms_proto = out.File
	file_hotel_v1_rpc_room_get_rooms_proto_goTypes = nil
	file_hotel_v1_rpc_room_get_rooms_proto_depIdxs = nil
}
