// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hotel/v1/rpc/hotel/get_hotels.proto

package hotelv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHotelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CitySlug      string                 `protobuf:"bytes,2,opt,name=city_slug,json=citySlug,proto3" json:"city_slug,omitempty"`
	Page          uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint64                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotelsRequest) Reset() {
	*x = GetHotelsRequest{}
	mi := &file_hotel_v1_rpc_hotel_get_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelsRequest) ProtoMessage() {}

func (x *GetHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_hotel_get_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelsRequest.ProtoReflect.Descriptor instead.
func (*GetHotelsRequest) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_hotel_get_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *GetHotelsRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GetHotelsRequest) GetCitySlug() string {
	if x != nil {
		return x.CitySlug
	}
	return ""
}

func (x *GetHotelsRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetHotelsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHotelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hotels        []*HotelShort          `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint64                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotelsResponse) Reset() {
	*x = GetHotelsResponse{}
	mi := &file_hotel_v1_rpc_hotel_get_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelsResponse) ProtoMessage() {}

func (x *GetHotelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_hotel_get_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelsResponse.ProtoReflect.Descriptor instead.
func (*GetHotelsResponse) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_hotel_get_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *GetHotelsResponse) GetHotels() []*HotelShort {
	if x != nil {
		return x.Hotels
	}
	return nil
}

func (x *GetHotelsResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetHotelsResponse) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetHotelsResponse) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_hotel_v1_rpc_hotel_get_hotels_proto protoreflect.FileDescriptor

const file_hotel_v1_rpc_hotel_get_hotels_proto_rawDesc = "" +
	"\n" +
	"#hotel/v1/rpc/hotel/get_hotels.proto\x12\bhotel.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bhotel/v1/models/hotel.proto\"\xc4\x01\n" +
	"\x10GetHotelsRequest\x124\n" +
	"\fcountry_code\x18\x01 \x01(\tB\x11\xbaH\x0er\f2\n" +
	"^[a-z]{2}$R\vcountryCode\x12<\n" +
	"\tcity_slug\x18\x02 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\bcitySlug\x12\x1b\n" +
	"\x04page\x18\x03 \x01(\x04B\a\xbaH\x042\x02(\x01R\x04page\x12\x1f\n" +
	"\x05limit\x18\x04 \x01(\x04B\t\xbaH\x062\x04\x18d(\x01R\x05limit\"\x8c\x01\n" +
	"\x11GetHotelsResponse\x12,\n" +
	"\x06hotels\x18\x01 \x03(\v2\x14.hotel.v1.HotelShortR\x06hotels\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x04R\x05limitB\x16Z\x14api/hotel/v1;hotelv1b\x06proto3"

var (
	file_hotel_v1_rpc_hotel_get_hotels_proto_rawDescOnce sync.Once
	file_hotel_v1_rpc_hotel_get_hotels_proto_rawDescData []byte
)

func file_hotel_v1_rpc_hotel_get_hotels_proto_rawDescGZIP() []byte {
	file_hotel_v1_rpc_hotel_get_hotels_proto_rawDescOnce.Do(func() {
		file_hotel_v1_rpc_hotel_get_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_hotel_get_hotels_proto_rawDesc), len(file_hotel_v1_rpc_hotel_get_hotels_proto_rawDesc)))
	})
	return file_hotel_v1_rpc_hotel_get_hotels_proto_rawDescData
}

var file_hotel_v1_rpc_hotel_get_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hotel_v1_rpc_hotel_get_hotels_proto_goTypes = []any{
	(*GetHotelsRequest)(nil),  // 0: hotel.v1.GetHotelsRequest
	(*GetHotelsResponse)(nil), // 1: hotel.v1.GetHotelsResponse
	(*HotelShort)(nil),        // 2: hotel.v1.HotelShort
}
var file_hotel_v1_rpc_hotel_get_hotels_proto_depIdxs = []int32{
	2, // 0: hotel.v1.GetHotelsResponse.hotels:type_name -> hotel.v1.HotelShort
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hotel_v1_rpc_hotel_get_hotels_proto_init() }
func file_hotel_v1_rpc_hotel_get_hotels_proto_init() {
	if File_hotel_v1_rpc_hotel_get_hotels_proto != nil {
		return
	}
	file_hotel_v1_models_hotel_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_hotel_get_hotels_proto_rawDesc), len(file_hotel_v1_rpc_hotel_get_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotel_v1_rpc_hotel_get_hotels_proto_goTypes,
		DependencyIndexes: file_hotel_v1_rpc_hotel_get_hotels_proto_depIdxs,
		MessageInfos:      file_hotel_v1_rpc_hotel_get_hotels_proto_msgTypes,
	}.Build()
	File_hotel_v1_rpc_hotel_get_hotels_proto = out.File
	file_hotel_v1_rpc_hotel_get_hotels_proto_goTypes = nil
	file_hotel_v1_rpc_hotel_get_hotels_proto_depIdxs = nil
}
