// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hotel/v1/rpc/room/get_room.proto

package hotelv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_hotel_v1_rpc_room_get_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_room_get_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_room_get_room_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	mi := &file_hotel_v1_rpc_room_get_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_room_get_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_room_get_room_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

var File_hotel_v1_rpc_room_get_room_proto protoreflect.FileDescriptor

const file_hotel_v1_rpc_room_get_room_proto_rawDesc = "" +
	"\n" +
	" hotel/v1/rpc/room/get_room.proto\x12\bhotel.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1ahotel/v1/models/room.proto\"*\n" +
	"\x0eGetRoomRequest\x12\x18\n" +
	"\x02id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"5\n" +
	"\x0fGetRoomResponse\x12\"\n" +
	"\x04room\x18\x01 \x01(\v2\x0e.hotel.v1.RoomR\x04roomB\x16Z\x14api/hotel/v1;hotelv1b\x06proto3"

var (
	file_hotel_v1_rpc_room_get_room_proto_rawDescOnce sync.Once
	file_hotel_v1_rpc_room_get_room_proto_rawDescData []byte
)

func file_hotel_v1_rpc_room_get_room_proto_rawDescGZIP() []byte {
	file_hotel_v1_rpc_room_get_room_proto_rawDescOnce.Do(func() {
		file_hotel_v1_rpc_room_get_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_room_get_room_proto_rawDesc), len(file_hotel_v1_rpc_room_get_room_proto_rawDesc)))
	})
	return file_hotel_v1_rpc_room_get_room_proto_rawDescData
}

var file_hotel_v1_rpc_room_get_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hotel_v1_rpc_room_get_room_proto_goTypes = []any{
	(*GetRoomRequest)(nil),  // 0: hotel.v1.GetRoomRequest
	(*GetRoomResponse)(nil), // 1: hotel.v1.GetRoomResponse
	(*Room)(nil),            // 2: hotel.v1.Room
}
var file_hotel_v1_rpc_room_get_room_proto_depIdxs = []int32{
	2, // 0: hotel.v1.GetRoomResponse.room:type_name -> hotel.v1.Room
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hotel_v1_rpc_room_get_room_proto_init() }
func file_hotel_v1_rpc_room_get_room_proto_init() {
	if File_hotel_v1_rpc_room_get_room_proto != nil {
		return
	}
	file_hotel_v1_models_room_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_room_get_room_proto_rawDesc), len(file_hotel_v1_rpc_room_get_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotel_v1_rpc_room_get_room_proto_goTypes,
		DependencyIndexes: file_hotel_v1_rpc_room_get_room_proto_depIdxs,
		MessageInfos:      file_hotel_v1_rpc_room_get_room_proto_msgTypes,
	}.Build()
	File_hotel_v1_rpc_room_get_room_proto = out.File
	file_hotel_v1_rpc_room_get_room_proto_goTypes = nil
	file_hotel_v1_rpc_room_get_room_proto_depIdxs = nil
}
