// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hotel/v1/models/room.proto

package hotelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,4,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Status        RoomStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=hotel.v1.RoomStatus" json:"status,omitempty"`
	Type          RoomType               `protobuf:"varint,6,opt,name=type,proto3,enum=hotel.v1.RoomType" json:"type,omitempty"`
	Price         string                 `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	Capacity      int64                  `protobuf:"varint,8,opt,name=capacity,proto3" json:"capacity,omitempty"`
	AreaSqm       float32                `protobuf:"fixed32,9,opt,name=area_sqm,json=areaSqm,proto3" json:"area_sqm,omitempty"`
	Floor         int64                  `protobuf:"varint,10,opt,name=floor,proto3" json:"floor,omitempty"`
	Amenities     []string               `protobuf:"bytes,11,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Images        []string               `protobuf:"bytes,12,rep,name=images,proto3" json:"images,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_hotel_v1_models_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_models_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_hotel_v1_models_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Room) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Room) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *Room) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

func (x *Room) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *Room) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Room) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Room) GetAreaSqm() float32 {
	if x != nil {
		return x.AreaSqm
	}
	return 0
}

func (x *Room) GetFloor() int64 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *Room) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *Room) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Room) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RoomShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,3,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Status        RoomStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=hotel.v1.RoomStatus" json:"status,omitempty"`
	Type          RoomType               `protobuf:"varint,5,opt,name=type,proto3,enum=hotel.v1.RoomType" json:"type,omitempty"`
	Price         string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Capacity      int64                  `protobuf:"varint,7,opt,name=capacity,proto3" json:"capacity,omitempty"`
	AreaSqm       float32                `protobuf:"fixed32,8,opt,name=area_sqm,json=areaSqm,proto3" json:"area_sqm,omitempty"`
	Amenities     []string               `protobuf:"bytes,9,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Images        []string               `protobuf:"bytes,10,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomShort) Reset() {
	*x = RoomShort{}
	mi := &file_hotel_v1_models_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomShort) ProtoMessage() {}

func (x *RoomShort) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_models_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomShort.ProtoReflect.Descriptor instead.
func (*RoomShort) Descriptor() ([]byte, []int) {
	return file_hotel_v1_models_room_proto_rawDescGZIP(), []int{1}
}

func (x *RoomShort) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomShort) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoomShort) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *RoomShort) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

func (x *RoomShort) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *RoomShort) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *RoomShort) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *RoomShort) GetAreaSqm() float32 {
	if x != nil {
		return x.AreaSqm
	}
	return 0
}

func (x *RoomShort) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *RoomShort) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type UpdateRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,2,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Type          RoomType               `protobuf:"varint,3,opt,name=type,proto3,enum=hotel.v1.RoomType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         string                 `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Capacity      int64                  `protobuf:"varint,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	AreaSqm       float32                `protobuf:"fixed32,7,opt,name=area_sqm,json=areaSqm,proto3" json:"area_sqm,omitempty"`
	Floor         int64                  `protobuf:"varint,8,opt,name=floor,proto3" json:"floor,omitempty"`
	Amenities     []string               `protobuf:"bytes,9,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Images        []string               `protobuf:"bytes,10,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoom) Reset() {
	*x = UpdateRoom{}
	mi := &file_hotel_v1_models_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoom) ProtoMessage() {}

func (x *UpdateRoom) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_models_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoom.ProtoReflect.Descriptor instead.
func (*UpdateRoom) Descriptor() ([]byte, []int) {
	return file_hotel_v1_models_room_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRoom) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateRoom) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *UpdateRoom) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *UpdateRoom) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRoom) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *UpdateRoom) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *UpdateRoom) GetAreaSqm() float32 {
	if x != nil {
		return x.AreaSqm
	}
	return 0
}

func (x *UpdateRoom) GetFloor() int64 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *UpdateRoom) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *UpdateRoom) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

var File_hotel_v1_models_room_proto protoreflect.FileDescriptor

const file_hotel_v1_models_room_proto_rawDesc = "" +
	"\n" +
	"\x1ahotel/v1/models/room.proto\x12\bhotel.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a hotel/v1/enums/room_status.proto\x1a\x1ehotel/v1/enums/room_type.proto\"\xe9\x03\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\vroom_number\x18\x04 \x01(\tR\n" +
	"roomNumber\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.hotel.v1.RoomStatusR\x06status\x12&\n" +
	"\x04type\x18\x06 \x01(\x0e2\x12.hotel.v1.RoomTypeR\x04type\x12\x14\n" +
	"\x05price\x18\a \x01(\tR\x05price\x12\x1a\n" +
	"\bcapacity\x18\b \x01(\x03R\bcapacity\x12\x19\n" +
	"\barea_sqm\x18\t \x01(\x02R\aareaSqm\x12\x14\n" +
	"\x05floor\x18\n" +
	" \x01(\x03R\x05floor\x12\x1c\n" +
	"\tamenities\x18\v \x03(\tR\tamenities\x12\x16\n" +
	"\x06images\x18\f \x03(\tR\x06images\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_description\"\xab\x02\n" +
	"\tRoomShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vroom_number\x18\x03 \x01(\tR\n" +
	"roomNumber\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.hotel.v1.RoomStatusR\x06status\x12&\n" +
	"\x04type\x18\x05 \x01(\x0e2\x12.hotel.v1.RoomTypeR\x04type\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x1a\n" +
	"\bcapacity\x18\a \x01(\x03R\bcapacity\x12\x19\n" +
	"\barea_sqm\x18\b \x01(\x02R\aareaSqm\x12\x1c\n" +
	"\tamenities\x18\t \x03(\tR\tamenities\x12\x16\n" +
	"\x06images\x18\n" +
	" \x03(\tR\x06images\"\xa6\x02\n" +
	"\n" +
	"UpdateRoom\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1f\n" +
	"\vroom_number\x18\x02 \x01(\tR\n" +
	"roomNumber\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.hotel.v1.RoomTypeR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\tR\x05price\x12\x1a\n" +
	"\bcapacity\x18\x06 \x01(\x03R\bcapacity\x12\x19\n" +
	"\barea_sqm\x18\a \x01(\x02R\aareaSqm\x12\x14\n" +
	"\x05floor\x18\b \x01(\x03R\x05floor\x12\x1c\n" +
	"\tamenities\x18\t \x03(\tR\tamenities\x12\x16\n" +
	"\x06images\x18\n" +
	" \x03(\tR\x06imagesB\x16Z\x14api/hotel/v1;hotelv1b\x06proto3"

var (
	file_hotel_v1_models_room_proto_rawDescOnce sync.Once
	file_hotel_v1_models_room_proto_rawDescData []byte
)

func file_hotel_v1_models_room_proto_rawDescGZIP() []byte {
	file_hotel_v1_models_room_proto_rawDescOnce.Do(func() {
		file_hotel_v1_models_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_v1_models_room_proto_rawDesc), len(file_hotel_v1_models_room_proto_rawDesc)))
	})
	return file_hotel_v1_models_room_proto_rawDescData
}

var file_hotel_v1_models_room_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hotel_v1_models_room_proto_goTypes = []any{
	(*Room)(nil),                  // 0: hotel.v1.Room
	(*RoomShort)(nil),             // 1: hotel.v1.RoomShort
	(*UpdateRoom)(nil),            // 2: hotel.v1.UpdateRoom
	(RoomStatus)(0),               // 3: hotel.v1.RoomStatus
	(RoomType)(0),                 // 4: hotel.v1.RoomType
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_hotel_v1_models_room_proto_depIdxs = []int32{
	3, // 0: hotel.v1.Room.status:type_name -> hotel.v1.RoomStatus
	4, // 1: hotel.v1.Room.type:type_name -> hotel.v1.RoomType
	5, // 2: hotel.v1.Room.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: hotel.v1.Room.updated_at:type_name -> google.protobuf.Timestamp
	3, // 4: hotel.v1.RoomShort.status:type_name -> hotel.v1.RoomStatus
	4, // 5: hotel.v1.RoomShort.type:type_name -> hotel.v1.RoomType
	4, // 6: hotel.v1.UpdateRoom.type:type_name -> hotel.v1.RoomType
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_hotel_v1_models_room_proto_init() }
func file_hotel_v1_models_room_proto_init() {
	if File_hotel_v1_models_room_proto != nil {
		return
	}
	file_hotel_v1_enums_room_status_proto_init()
	file_hotel_v1_enums_room_type_proto_init()
	file_hotel_v1_models_room_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_v1_models_room_proto_rawDesc), len(file_hotel_v1_models_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotel_v1_models_room_proto_goTypes,
		DependencyIndexes: file_hotel_v1_models_room_proto_depIdxs,
		MessageInfos:      file_hotel_v1_models_room_proto_msgTypes,
	}.Build()
	File_hotel_v1_models_room_proto = out.File
	file_hotel_v1_models_room_proto_goTypes = nil
	file_hotel_v1_models_room_proto_depIdxs = nil
}
