// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hotel/v1/enums/room_type.proto

package hotelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomType int32

const (
	RoomType_ROOM_TYPE_UNSPECIFIED  RoomType = 0
	RoomType_ROOM_TYPE_SINGLE       RoomType = 1
	RoomType_ROOM_TYPE_DOUBLE       RoomType = 2
	RoomType_ROOM_TYPE_SUITE        RoomType = 3
	RoomType_ROOM_TYPE_DELUXE       RoomType = 4
	RoomType_ROOM_TYPE_FAMILY       RoomType = 5
	RoomType_ROOM_TYPE_PRESIDENTIAL RoomType = 6
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "ROOM_TYPE_UNSPECIFIED",
		1: "ROOM_TYPE_SINGLE",
		2: "ROOM_TYPE_DOUBLE",
		3: "ROOM_TYPE_SUITE",
		4: "ROOM_TYPE_DELUXE",
		5: "ROOM_TYPE_FAMILY",
		6: "ROOM_TYPE_PRESIDENTIAL",
	}
	RoomType_value = map[string]int32{
		"ROOM_TYPE_UNSPECIFIED":  0,
		"ROOM_TYPE_SINGLE":       1,
		"ROOM_TYPE_DOUBLE":       2,
		"ROOM_TYPE_SUITE":        3,
		"ROOM_TYPE_DELUXE":       4,
		"ROOM_TYPE_FAMILY":       5,
		"ROOM_TYPE_PRESIDENTIAL": 6,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_hotel_v1_enums_room_type_proto_enumTypes[0].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_hotel_v1_enums_room_type_proto_enumTypes[0]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_hotel_v1_enums_room_type_proto_rawDescGZIP(), []int{0}
}

var File_hotel_v1_enums_room_type_proto protoreflect.FileDescriptor

const file_hotel_v1_enums_room_type_proto_rawDesc = "" +
	"\n" +
	"\x1ehotel/v1/enums/room_type.proto\x12\bhotel.v1*\xae\x01\n" +
	"\bRoomType\x12\x19\n" +
	"\x15ROOM_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ROOM_TYPE_SINGLE\x10\x01\x12\x14\n" +
	"\x10ROOM_TYPE_DOUBLE\x10\x02\x12\x13\n" +
	"\x0fROOM_TYPE_SUITE\x10\x03\x12\x14\n" +
	"\x10ROOM_TYPE_DELUXE\x10\x04\x12\x14\n" +
	"\x10ROOM_TYPE_FAMILY\x10\x05\x12\x1a\n" +
	"\x16ROOM_TYPE_PRESIDENTIAL\x10\x06B\x16Z\x14api/hotel/v1;hotelv1b\x06proto3"

var (
	file_hotel_v1_enums_room_type_proto_rawDescOnce sync.Once
	file_hotel_v1_enums_room_type_proto_rawDescData []byte
)

func file_hotel_v1_enums_room_type_proto_rawDescGZIP() []byte {
	file_hotel_v1_enums_room_type_proto_rawDescOnce.Do(func() {
		file_hotel_v1_enums_room_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_v1_enums_room_type_proto_rawDesc), len(file_hotel_v1_enums_room_type_proto_rawDesc)))
	})
	return file_hotel_v1_enums_room_type_proto_rawDescData
}

var file_hotel_v1_enums_room_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hotel_v1_enums_room_type_proto_goTypes = []any{
	(RoomType)(0), // 0: hotel.v1.RoomType
}
var file_hotel_v1_enums_room_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hotel_v1_enums_room_type_proto_init() }
func file_hotel_v1_enums_room_type_proto_init() {
	if File_hotel_v1_enums_room_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_v1_enums_room_type_proto_rawDesc), len(file_hotel_v1_enums_room_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotel_v1_enums_room_type_proto_goTypes,
		DependencyIndexes: file_hotel_v1_enums_room_type_proto_depIdxs,
		EnumInfos:         file_hotel_v1_enums_room_type_proto_enumTypes,
	}.Build()
	File_hotel_v1_enums_room_type_proto = out.File
	file_hotel_v1_enums_room_type_proto_goTypes = nil
	file_hotel_v1_enums_room_type_proto_depIdxs = nil
}
