// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hotel/v1/rpc/update_hotel_title.proto

package hotelv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateHotelTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CitySlug      string                 `protobuf:"bytes,2,opt,name=city_slug,json=citySlug,proto3" json:"city_slug,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHotelTitleRequest) Reset() {
	*x = UpdateHotelTitleRequest{}
	mi := &file_hotel_v1_rpc_update_hotel_title_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHotelTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHotelTitleRequest) ProtoMessage() {}

func (x *UpdateHotelTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_update_hotel_title_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHotelTitleRequest.ProtoReflect.Descriptor instead.
func (*UpdateHotelTitleRequest) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_update_hotel_title_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateHotelTitleRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *UpdateHotelTitleRequest) GetCitySlug() string {
	if x != nil {
		return x.CitySlug
	}
	return ""
}

func (x *UpdateHotelTitleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateHotelTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdateHotelTitleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hotel         *UpdateHotelTitle      `protobuf:"bytes,1,opt,name=hotel,proto3" json:"hotel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHotelTitleResponse) Reset() {
	*x = UpdateHotelTitleResponse{}
	mi := &file_hotel_v1_rpc_update_hotel_title_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHotelTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHotelTitleResponse) ProtoMessage() {}

func (x *UpdateHotelTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_update_hotel_title_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHotelTitleResponse.ProtoReflect.Descriptor instead.
func (*UpdateHotelTitleResponse) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_update_hotel_title_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateHotelTitleResponse) GetHotel() *UpdateHotelTitle {
	if x != nil {
		return x.Hotel
	}
	return nil
}

var File_hotel_v1_rpc_update_hotel_title_proto protoreflect.FileDescriptor

const file_hotel_v1_rpc_update_hotel_title_proto_rawDesc = "" +
	"\n" +
	"%hotel/v1/rpc/update_hotel_title.proto\x12\bhotel.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bhotel/v1/models/hotel.proto\"\xe0\x01\n" +
	"\x17UpdateHotelTitleRequest\x124\n" +
	"\fcountry_code\x18\x01 \x01(\tB\x11\xbaH\x0er\f2\n" +
	"^[a-z]{2}$R\vcountryCode\x12<\n" +
	"\tcity_slug\x18\x02 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\bcitySlug\x123\n" +
	"\x04slug\x18\x03 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04slug\x12\x1c\n" +
	"\x05title\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05title\"L\n" +
	"\x18UpdateHotelTitleResponse\x120\n" +
	"\x05hotel\x18\x01 \x01(\v2\x1a.hotel.v1.UpdateHotelTitleR\x05hotelB\x16Z\x14api/hotel/v1;hotelv1b\x06proto3"

var (
	file_hotel_v1_rpc_update_hotel_title_proto_rawDescOnce sync.Once
	file_hotel_v1_rpc_update_hotel_title_proto_rawDescData []byte
)

func file_hotel_v1_rpc_update_hotel_title_proto_rawDescGZIP() []byte {
	file_hotel_v1_rpc_update_hotel_title_proto_rawDescOnce.Do(func() {
		file_hotel_v1_rpc_update_hotel_title_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_update_hotel_title_proto_rawDesc), len(file_hotel_v1_rpc_update_hotel_title_proto_rawDesc)))
	})
	return file_hotel_v1_rpc_update_hotel_title_proto_rawDescData
}

var file_hotel_v1_rpc_update_hotel_title_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hotel_v1_rpc_update_hotel_title_proto_goTypes = []any{
	(*UpdateHotelTitleRequest)(nil),  // 0: hotel.v1.UpdateHotelTitleRequest
	(*UpdateHotelTitleResponse)(nil), // 1: hotel.v1.UpdateHotelTitleResponse
	(*UpdateHotelTitle)(nil),         // 2: hotel.v1.UpdateHotelTitle
}
var file_hotel_v1_rpc_update_hotel_title_proto_depIdxs = []int32{
	2, // 0: hotel.v1.UpdateHotelTitleResponse.hotel:type_name -> hotel.v1.UpdateHotelTitle
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hotel_v1_rpc_update_hotel_title_proto_init() }
func file_hotel_v1_rpc_update_hotel_title_proto_init() {
	if File_hotel_v1_rpc_update_hotel_title_proto != nil {
		return
	}
	file_hotel_v1_models_hotel_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_update_hotel_title_proto_rawDesc), len(file_hotel_v1_rpc_update_hotel_title_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotel_v1_rpc_update_hotel_title_proto_goTypes,
		DependencyIndexes: file_hotel_v1_rpc_update_hotel_title_proto_depIdxs,
		MessageInfos:      file_hotel_v1_rpc_update_hotel_title_proto_msgTypes,
	}.Build()
	File_hotel_v1_rpc_update_hotel_title_proto = out.File
	file_hotel_v1_rpc_update_hotel_title_proto_goTypes = nil
	file_hotel_v1_rpc_update_hotel_title_proto_depIdxs = nil
}
