// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hotel/v1/rpc/room/update_room.proto

package hotelv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,4,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Type          RoomType               `protobuf:"varint,5,opt,name=type,proto3,enum=hotel.v1.RoomType" json:"type,omitempty"`
	Price         string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Capacity      int64                  `protobuf:"varint,7,opt,name=capacity,proto3" json:"capacity,omitempty"`
	AreaSqm       float32                `protobuf:"fixed32,8,opt,name=area_sqm,json=areaSqm,proto3" json:"area_sqm,omitempty"`
	Floor         int64                  `protobuf:"varint,9,opt,name=floor,proto3" json:"floor,omitempty"`
	Amenities     []string               `protobuf:"bytes,10,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Images        []string               `protobuf:"bytes,11,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	mi := &file_hotel_v1_rpc_room_update_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_room_update_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_room_update_room_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoomRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateRoomRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRoomRequest) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *UpdateRoomRequest) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *UpdateRoomRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *UpdateRoomRequest) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *UpdateRoomRequest) GetAreaSqm() float32 {
	if x != nil {
		return x.AreaSqm
	}
	return 0
}

func (x *UpdateRoomRequest) GetFloor() int64 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *UpdateRoomRequest) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *UpdateRoomRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type UpdateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *UpdateRoom            `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomResponse) Reset() {
	*x = UpdateRoomResponse{}
	mi := &file_hotel_v1_rpc_room_update_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomResponse) ProtoMessage() {}

func (x *UpdateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_room_update_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomResponse) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_room_update_room_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRoomResponse) GetRoom() *UpdateRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

var File_hotel_v1_rpc_room_update_room_proto protoreflect.FileDescriptor

const file_hotel_v1_rpc_room_update_room_proto_rawDesc = "" +
	"\n" +
	"#hotel/v1/rpc/room/update_room.proto\x12\bhotel.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1ahotel/v1/models/room.proto\x1a\x1ehotel/v1/enums/room_type.proto\"\x97\x03\n" +
	"\x11UpdateRoomRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1c\n" +
	"\x05title\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05title\x12(\n" +
	"\vdescription\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\vdescription\x12'\n" +
	"\vroom_number\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"roomNumber\x12.\n" +
	"\x04type\x18\x05 \x01(\x0e2\x12.hotel.v1.RoomTypeB\x06\xbaH\x03\xc8\x01\x01R\x04type\x12\x1c\n" +
	"\x05price\x18\x06 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05price\x12\"\n" +
	"\bcapacity\x18\a \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\bcapacity\x12!\n" +
	"\barea_sqm\x18\b \x01(\x02B\x06\xbaH\x03\xc8\x01\x01R\aareaSqm\x12\x1c\n" +
	"\x05floor\x18\t \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\x05floor\x12$\n" +
	"\tamenities\x18\n" +
	" \x03(\tB\x06\xbaH\x03\xc8\x01\x01R\tamenities\x12\x1e\n" +
	"\x06images\x18\v \x03(\tB\x06\xbaH\x03\xc8\x01\x01R\x06images\">\n" +
	"\x12UpdateRoomResponse\x12(\n" +
	"\x04room\x18\x01 \x01(\v2\x14.hotel.v1.UpdateRoomR\x04roomB\x16Z\x14api/hotel/v1;hotelv1b\x06proto3"

var (
	file_hotel_v1_rpc_room_update_room_proto_rawDescOnce sync.Once
	file_hotel_v1_rpc_room_update_room_proto_rawDescData []byte
)

func file_hotel_v1_rpc_room_update_room_proto_rawDescGZIP() []byte {
	file_hotel_v1_rpc_room_update_room_proto_rawDescOnce.Do(func() {
		file_hotel_v1_rpc_room_update_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_room_update_room_proto_rawDesc), len(file_hotel_v1_rpc_room_update_room_proto_rawDesc)))
	})
	return file_hotel_v1_rpc_room_update_room_proto_rawDescData
}

var file_hotel_v1_rpc_room_update_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hotel_v1_rpc_room_update_room_proto_goTypes = []any{
	(*UpdateRoomRequest)(nil),  // 0: hotel.v1.UpdateRoomRequest
	(*UpdateRoomResponse)(nil), // 1: hotel.v1.UpdateRoomResponse
	(RoomType)(0),              // 2: hotel.v1.RoomType
	(*UpdateRoom)(nil),         // 3: hotel.v1.UpdateRoom
}
var file_hotel_v1_rpc_room_update_room_proto_depIdxs = []int32{
	2, // 0: hotel.v1.UpdateRoomRequest.type:type_name -> hotel.v1.RoomType
	3, // 1: hotel.v1.UpdateRoomResponse.room:type_name -> hotel.v1.UpdateRoom
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hotel_v1_rpc_room_update_room_proto_init() }
func file_hotel_v1_rpc_room_update_room_proto_init() {
	if File_hotel_v1_rpc_room_update_room_proto != nil {
		return
	}
	file_hotel_v1_models_room_proto_init()
	file_hotel_v1_enums_room_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_room_update_room_proto_rawDesc), len(file_hotel_v1_rpc_room_update_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotel_v1_rpc_room_update_room_proto_goTypes,
		DependencyIndexes: file_hotel_v1_rpc_room_update_room_proto_depIdxs,
		MessageInfos:      file_hotel_v1_rpc_room_update_room_proto_msgTypes,
	}.Build()
	File_hotel_v1_rpc_room_update_room_proto = out.File
	file_hotel_v1_rpc_room_update_room_proto_goTypes = nil
	file_hotel_v1_rpc_room_update_room_proto_depIdxs = nil
}
