// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hotel/v1/rpc/room/update_room_status.proto

package hotelv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateRoomStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        RoomStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=hotel.v1.RoomStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomStatusRequest) Reset() {
	*x = UpdateRoomStatusRequest{}
	mi := &file_hotel_v1_rpc_room_update_room_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomStatusRequest) ProtoMessage() {}

func (x *UpdateRoomStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_room_update_room_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomStatusRequest) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_room_update_room_status_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRoomStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoomStatusRequest) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

type UpdateRoomStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        RoomStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=hotel.v1.RoomStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomStatusResponse) Reset() {
	*x = UpdateRoomStatusResponse{}
	mi := &file_hotel_v1_rpc_room_update_room_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomStatusResponse) ProtoMessage() {}

func (x *UpdateRoomStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_v1_rpc_room_update_room_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomStatusResponse) Descriptor() ([]byte, []int) {
	return file_hotel_v1_rpc_room_update_room_status_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRoomStatusResponse) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

var File_hotel_v1_rpc_room_update_room_status_proto protoreflect.FileDescriptor

const file_hotel_v1_rpc_room_update_room_status_proto_rawDesc = "" +
	"\n" +
	"*hotel/v1/rpc/room/update_room_status.proto\x12\bhotel.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1ahotel/v1/models/room.proto\x1a hotel/v1/enums/room_status.proto\"i\n" +
	"\x17UpdateRoomStatusRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x124\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.hotel.v1.RoomStatusB\x06\xbaH\x03\xc8\x01\x01R\x06status\"H\n" +
	"\x18UpdateRoomStatusResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.hotel.v1.RoomStatusR\x06statusB\x16Z\x14api/hotel/v1;hotelv1b\x06proto3"

var (
	file_hotel_v1_rpc_room_update_room_status_proto_rawDescOnce sync.Once
	file_hotel_v1_rpc_room_update_room_status_proto_rawDescData []byte
)

func file_hotel_v1_rpc_room_update_room_status_proto_rawDescGZIP() []byte {
	file_hotel_v1_rpc_room_update_room_status_proto_rawDescOnce.Do(func() {
		file_hotel_v1_rpc_room_update_room_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_room_update_room_status_proto_rawDesc), len(file_hotel_v1_rpc_room_update_room_status_proto_rawDesc)))
	})
	return file_hotel_v1_rpc_room_update_room_status_proto_rawDescData
}

var file_hotel_v1_rpc_room_update_room_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hotel_v1_rpc_room_update_room_status_proto_goTypes = []any{
	(*UpdateRoomStatusRequest)(nil),  // 0: hotel.v1.UpdateRoomStatusRequest
	(*UpdateRoomStatusResponse)(nil), // 1: hotel.v1.UpdateRoomStatusResponse
	(RoomStatus)(0),                  // 2: hotel.v1.RoomStatus
}
var file_hotel_v1_rpc_room_update_room_status_proto_depIdxs = []int32{
	2, // 0: hotel.v1.UpdateRoomStatusRequest.status:type_name -> hotel.v1.RoomStatus
	2, // 1: hotel.v1.UpdateRoomStatusResponse.status:type_name -> hotel.v1.RoomStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hotel_v1_rpc_room_update_room_status_proto_init() }
func file_hotel_v1_rpc_room_update_room_status_proto_init() {
	if File_hotel_v1_rpc_room_update_room_status_proto != nil {
		return
	}
	file_hotel_v1_models_room_proto_init()
	file_hotel_v1_enums_room_status_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_v1_rpc_room_update_room_status_proto_rawDesc), len(file_hotel_v1_rpc_room_update_room_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotel_v1_rpc_room_update_room_status_proto_goTypes,
		DependencyIndexes: file_hotel_v1_rpc_room_update_room_status_proto_depIdxs,
		MessageInfos:      file_hotel_v1_rpc_room_update_room_status_proto_msgTypes,
	}.Build()
	File_hotel_v1_rpc_room_update_room_status_proto = out.File
	file_hotel_v1_rpc_room_update_room_status_proto_goTypes = nil
	file_hotel_v1_rpc_room_update_room_status_proto_depIdxs = nil
}
