// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "auth/internal/repository/postgres/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// UserCreate provides a mock function with given fields: ctx, user
func (_m *MockRepository) UserCreate(ctx context.Context, user models.UserCreate) (*models.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UserCreate")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserCreate) (*models.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserCreate) *models.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserCreate) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UserCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserCreate'
type MockRepository_UserCreate_Call struct {
	*mock.Call
}

// UserCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - user models.UserCreate
func (_e *MockRepository_Expecter) UserCreate(ctx interface{}, user interface{}) *MockRepository_UserCreate_Call {
	return &MockRepository_UserCreate_Call{Call: _e.mock.On("UserCreate", ctx, user)}
}

func (_c *MockRepository_UserCreate_Call) Run(run func(ctx context.Context, user models.UserCreate)) *MockRepository_UserCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserCreate))
	})
	return _c
}

func (_c *MockRepository_UserCreate_Call) Return(_a0 *models.User, _a1 error) *MockRepository_UserCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UserCreate_Call) RunAndReturn(run func(context.Context, models.UserCreate) (*models.User, error)) *MockRepository_UserCreate_Call {
	_c.Call.Return(run)
	return _c
}

// UserDeleteByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) UserDeleteByID(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserDeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UserDeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserDeleteByID'
type MockRepository_UserDeleteByID_Call struct {
	*mock.Call
}

// UserDeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepository_Expecter) UserDeleteByID(ctx interface{}, id interface{}) *MockRepository_UserDeleteByID_Call {
	return &MockRepository_UserDeleteByID_Call{Call: _e.mock.On("UserDeleteByID", ctx, id)}
}

func (_c *MockRepository_UserDeleteByID_Call) Run(run func(ctx context.Context, id int64)) *MockRepository_UserDeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepository_UserDeleteByID_Call) Return(_a0 error) *MockRepository_UserDeleteByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UserDeleteByID_Call) RunAndReturn(run func(context.Context, int64) error) *MockRepository_UserDeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// UserGetAll provides a mock function with given fields: ctx, limit, offset
func (_m *MockRepository) UserGetAll(ctx context.Context, limit uint64, offset uint64) ([]models.User, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for UserGetAll")
	}

	var r0 []models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]models.User, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) []models.User); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UserGetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserGetAll'
type MockRepository_UserGetAll_Call struct {
	*mock.Call
}

// UserGetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - limit uint64
//   - offset uint64
func (_e *MockRepository_Expecter) UserGetAll(ctx interface{}, limit interface{}, offset interface{}) *MockRepository_UserGetAll_Call {
	return &MockRepository_UserGetAll_Call{Call: _e.mock.On("UserGetAll", ctx, limit, offset)}
}

func (_c *MockRepository_UserGetAll_Call) Run(run func(ctx context.Context, limit uint64, offset uint64)) *MockRepository_UserGetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *MockRepository_UserGetAll_Call) Return(_a0 []models.User, _a1 error) *MockRepository_UserGetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UserGetAll_Call) RunAndReturn(run func(context.Context, uint64, uint64) ([]models.User, error)) *MockRepository_UserGetAll_Call {
	_c.Call.Return(run)
	return _c
}

// UserGetByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) UserGetByID(ctx context.Context, id int64) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserGetByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UserGetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserGetByID'
type MockRepository_UserGetByID_Call struct {
	*mock.Call
}

// UserGetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepository_Expecter) UserGetByID(ctx interface{}, id interface{}) *MockRepository_UserGetByID_Call {
	return &MockRepository_UserGetByID_Call{Call: _e.mock.On("UserGetByID", ctx, id)}
}

func (_c *MockRepository_UserGetByID_Call) Run(run func(ctx context.Context, id int64)) *MockRepository_UserGetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepository_UserGetByID_Call) Return(_a0 *models.User, _a1 error) *MockRepository_UserGetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UserGetByID_Call) RunAndReturn(run func(context.Context, int64) (*models.User, error)) *MockRepository_UserGetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UserGetCredentialsByEmail provides a mock function with given fields: ctx, email
func (_m *MockRepository) UserGetCredentialsByEmail(ctx context.Context, email string) (*models.UserCredentials, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UserGetCredentialsByEmail")
	}

	var r0 *models.UserCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.UserCredentials, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.UserCredentials); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UserGetCredentialsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserGetCredentialsByEmail'
type MockRepository_UserGetCredentialsByEmail_Call struct {
	*mock.Call
}

// UserGetCredentialsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepository_Expecter) UserGetCredentialsByEmail(ctx interface{}, email interface{}) *MockRepository_UserGetCredentialsByEmail_Call {
	return &MockRepository_UserGetCredentialsByEmail_Call{Call: _e.mock.On("UserGetCredentialsByEmail", ctx, email)}
}

func (_c *MockRepository_UserGetCredentialsByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRepository_UserGetCredentialsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_UserGetCredentialsByEmail_Call) Return(_a0 *models.UserCredentials, _a1 error) *MockRepository_UserGetCredentialsByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UserGetCredentialsByEmail_Call) RunAndReturn(run func(context.Context, string) (*models.UserCredentials, error)) *MockRepository_UserGetCredentialsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UserUpdateByID provides a mock function with given fields: ctx, user
func (_m *MockRepository) UserUpdateByID(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UserUpdateByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UserUpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserUpdateByID'
type MockRepository_UserUpdateByID_Call struct {
	*mock.Call
}

// UserUpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockRepository_Expecter) UserUpdateByID(ctx interface{}, user interface{}) *MockRepository_UserUpdateByID_Call {
	return &MockRepository_UserUpdateByID_Call{Call: _e.mock.On("UserUpdateByID", ctx, user)}
}

func (_c *MockRepository_UserUpdateByID_Call) Run(run func(ctx context.Context, user *models.User)) *MockRepository_UserUpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockRepository_UserUpdateByID_Call) Return(_a0 error) *MockRepository_UserUpdateByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UserUpdateByID_Call) RunAndReturn(run func(context.Context, *models.User) error) *MockRepository_UserUpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
