// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: booking/v1/booking_service.proto

package bookingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_booking_v1_booking_service_proto protoreflect.FileDescriptor

const file_booking_v1_booking_service_proto_rawDesc = "" +
	"\n" +
	" booking/v1/booking_service.proto\x12\n" +
	"booking.v1\x1a#booking/v1/rpc/create_booking.proto\x1a!booking/v1/rpc/get_bookings.proto\x1a booking/v1/rpc/get_booking.proto2\x83\x02\n" +
	"\x0eBookingService\x12T\n" +
	"\rCreateBooking\x12 .booking.v1.CreateBookingRequest\x1a!.booking.v1.CreateBookingResponse\x12N\n" +
	"\vGetBookings\x12\x1e.booking.v1.GetBookingsRequest\x1a\x1f.booking.v1.GetBookingsResponse\x12K\n" +
	"\n" +
	"GetBooking\x12\x1d.booking.v1.GetBookingRequest\x1a\x1e.booking.v1.GetBookingResponseB\x1aZ\x18api/booking/v1;bookingv1b\x06proto3"

var file_booking_v1_booking_service_proto_goTypes = []any{
	(*CreateBookingRequest)(nil),  // 0: booking.v1.CreateBookingRequest
	(*GetBookingsRequest)(nil),    // 1: booking.v1.GetBookingsRequest
	(*GetBookingRequest)(nil),     // 2: booking.v1.GetBookingRequest
	(*CreateBookingResponse)(nil), // 3: booking.v1.CreateBookingResponse
	(*GetBookingsResponse)(nil),   // 4: booking.v1.GetBookingsResponse
	(*GetBookingResponse)(nil),    // 5: booking.v1.GetBookingResponse
}
var file_booking_v1_booking_service_proto_depIdxs = []int32{
	0, // 0: booking.v1.BookingService.CreateBooking:input_type -> booking.v1.CreateBookingRequest
	1, // 1: booking.v1.BookingService.GetBookings:input_type -> booking.v1.GetBookingsRequest
	2, // 2: booking.v1.BookingService.GetBooking:input_type -> booking.v1.GetBookingRequest
	3, // 3: booking.v1.BookingService.CreateBooking:output_type -> booking.v1.CreateBookingResponse
	4, // 4: booking.v1.BookingService.GetBookings:output_type -> booking.v1.GetBookingsResponse
	5, // 5: booking.v1.BookingService.GetBooking:output_type -> booking.v1.GetBookingResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_booking_v1_booking_service_proto_init() }
func file_booking_v1_booking_service_proto_init() {
	if File_booking_v1_booking_service_proto != nil {
		return
	}
	file_booking_v1_rpc_create_booking_proto_init()
	file_booking_v1_rpc_get_bookings_proto_init()
	file_booking_v1_rpc_get_booking_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_booking_service_proto_rawDesc), len(file_booking_v1_booking_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_v1_booking_service_proto_goTypes,
		DependencyIndexes: file_booking_v1_booking_service_proto_depIdxs,
	}.Build()
	File_booking_v1_booking_service_proto = out.File
	file_booking_v1_booking_service_proto_goTypes = nil
	file_booking_v1_booking_service_proto_depIdxs = nil
}
