// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: booking/v1/models/booking_room.proto

package bookingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookingRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Adults        uint32                 `protobuf:"varint,3,opt,name=adults,proto3" json:"adults,omitempty"`
	Children      uint32                 `protobuf:"varint,4,opt,name=children,proto3" json:"children,omitempty"`
	PricePerNight string                 `protobuf:"bytes,5,opt,name=price_per_night,json=pricePerNight,proto3" json:"price_per_night,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingRoom) Reset() {
	*x = BookingRoom{}
	mi := &file_booking_v1_models_booking_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRoom) ProtoMessage() {}

func (x *BookingRoom) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_models_booking_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRoom.ProtoReflect.Descriptor instead.
func (*BookingRoom) Descriptor() ([]byte, []int) {
	return file_booking_v1_models_booking_room_proto_rawDescGZIP(), []int{0}
}

func (x *BookingRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookingRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *BookingRoom) GetAdults() uint32 {
	if x != nil {
		return x.Adults
	}
	return 0
}

func (x *BookingRoom) GetChildren() uint32 {
	if x != nil {
		return x.Children
	}
	return 0
}

func (x *BookingRoom) GetPricePerNight() string {
	if x != nil {
		return x.PricePerNight
	}
	return ""
}

type BookingRoomWithLock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Adults        uint32                 `protobuf:"varint,3,opt,name=adults,proto3" json:"adults,omitempty"`
	Children      uint32                 `protobuf:"varint,4,opt,name=children,proto3" json:"children,omitempty"`
	PricePerNight string                 `protobuf:"bytes,5,opt,name=price_per_night,json=pricePerNight,proto3" json:"price_per_night,omitempty"`
	RoomLock      *RoomLockShort         `protobuf:"bytes,6,opt,name=room_lock,json=roomLock,proto3" json:"room_lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingRoomWithLock) Reset() {
	*x = BookingRoomWithLock{}
	mi := &file_booking_v1_models_booking_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingRoomWithLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRoomWithLock) ProtoMessage() {}

func (x *BookingRoomWithLock) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_models_booking_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRoomWithLock.ProtoReflect.Descriptor instead.
func (*BookingRoomWithLock) Descriptor() ([]byte, []int) {
	return file_booking_v1_models_booking_room_proto_rawDescGZIP(), []int{1}
}

func (x *BookingRoomWithLock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookingRoomWithLock) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *BookingRoomWithLock) GetAdults() uint32 {
	if x != nil {
		return x.Adults
	}
	return 0
}

func (x *BookingRoomWithLock) GetChildren() uint32 {
	if x != nil {
		return x.Children
	}
	return 0
}

func (x *BookingRoomWithLock) GetPricePerNight() string {
	if x != nil {
		return x.PricePerNight
	}
	return ""
}

func (x *BookingRoomWithLock) GetRoomLock() *RoomLockShort {
	if x != nil {
		return x.RoomLock
	}
	return nil
}

var File_booking_v1_models_booking_room_proto protoreflect.FileDescriptor

const file_booking_v1_models_booking_room_proto_rawDesc = "" +
	"\n" +
	"$booking/v1/models/booking_room.proto\x12\n" +
	"booking.v1\x1a!booking/v1/models/room_lock.proto\"\x92\x01\n" +
	"\vBookingRoom\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06adults\x18\x03 \x01(\rR\x06adults\x12\x1a\n" +
	"\bchildren\x18\x04 \x01(\rR\bchildren\x12&\n" +
	"\x0fprice_per_night\x18\x05 \x01(\tR\rpricePerNight\"\xd2\x01\n" +
	"\x13BookingRoomWithLock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06adults\x18\x03 \x01(\rR\x06adults\x12\x1a\n" +
	"\bchildren\x18\x04 \x01(\rR\bchildren\x12&\n" +
	"\x0fprice_per_night\x18\x05 \x01(\tR\rpricePerNight\x126\n" +
	"\troom_lock\x18\x06 \x01(\v2\x19.booking.v1.RoomLockShortR\broomLockB\x1aZ\x18api/booking/v1;bookingv1b\x06proto3"

var (
	file_booking_v1_models_booking_room_proto_rawDescOnce sync.Once
	file_booking_v1_models_booking_room_proto_rawDescData []byte
)

func file_booking_v1_models_booking_room_proto_rawDescGZIP() []byte {
	file_booking_v1_models_booking_room_proto_rawDescOnce.Do(func() {
		file_booking_v1_models_booking_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_models_booking_room_proto_rawDesc), len(file_booking_v1_models_booking_room_proto_rawDesc)))
	})
	return file_booking_v1_models_booking_room_proto_rawDescData
}

var file_booking_v1_models_booking_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_booking_v1_models_booking_room_proto_goTypes = []any{
	(*BookingRoom)(nil),         // 0: booking.v1.BookingRoom
	(*BookingRoomWithLock)(nil), // 1: booking.v1.BookingRoomWithLock
	(*RoomLockShort)(nil),       // 2: booking.v1.RoomLockShort
}
var file_booking_v1_models_booking_room_proto_depIdxs = []int32{
	2, // 0: booking.v1.BookingRoomWithLock.room_lock:type_name -> booking.v1.RoomLockShort
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_booking_v1_models_booking_room_proto_init() }
func file_booking_v1_models_booking_room_proto_init() {
	if File_booking_v1_models_booking_room_proto != nil {
		return
	}
	file_booking_v1_models_room_lock_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_models_booking_room_proto_rawDesc), len(file_booking_v1_models_booking_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_booking_v1_models_booking_room_proto_goTypes,
		DependencyIndexes: file_booking_v1_models_booking_room_proto_depIdxs,
		MessageInfos:      file_booking_v1_models_booking_room_proto_msgTypes,
	}.Build()
	File_booking_v1_models_booking_room_proto = out.File
	file_booking_v1_models_booking_room_proto_goTypes = nil
	file_booking_v1_models_booking_room_proto_depIdxs = nil
}
