// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: booking/v1/rpc/delete_booking.proto

package bookingv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookingRequest) Reset() {
	*x = DeleteBookingRequest{}
	mi := &file_booking_v1_rpc_delete_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookingRequest) ProtoMessage() {}

func (x *DeleteBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_rpc_delete_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookingRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_rpc_delete_booking_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteBookingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookingResponse) Reset() {
	*x = DeleteBookingResponse{}
	mi := &file_booking_v1_rpc_delete_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookingResponse) ProtoMessage() {}

func (x *DeleteBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_rpc_delete_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookingResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_rpc_delete_booking_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_booking_v1_rpc_delete_booking_proto protoreflect.FileDescriptor

const file_booking_v1_rpc_delete_booking_proto_rawDesc = "" +
	"\n" +
	"#booking/v1/rpc/delete_booking.proto\x12\n" +
	"booking.v1\x1a\x1bbuf/validate/validate.proto\x1a%booking/v1/enums/booking_status.proto\"0\n" +
	"\x14DeleteBookingRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"1\n" +
	"\x15DeleteBookingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\x1aZ\x18api/booking/v1;bookingv1b\x06proto3"

var (
	file_booking_v1_rpc_delete_booking_proto_rawDescOnce sync.Once
	file_booking_v1_rpc_delete_booking_proto_rawDescData []byte
)

func file_booking_v1_rpc_delete_booking_proto_rawDescGZIP() []byte {
	file_booking_v1_rpc_delete_booking_proto_rawDescOnce.Do(func() {
		file_booking_v1_rpc_delete_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_rpc_delete_booking_proto_rawDesc), len(file_booking_v1_rpc_delete_booking_proto_rawDesc)))
	})
	return file_booking_v1_rpc_delete_booking_proto_rawDescData
}

var file_booking_v1_rpc_delete_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_booking_v1_rpc_delete_booking_proto_goTypes = []any{
	(*DeleteBookingRequest)(nil),  // 0: booking.v1.DeleteBookingRequest
	(*DeleteBookingResponse)(nil), // 1: booking.v1.DeleteBookingResponse
}
var file_booking_v1_rpc_delete_booking_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_booking_v1_rpc_delete_booking_proto_init() }
func file_booking_v1_rpc_delete_booking_proto_init() {
	if File_booking_v1_rpc_delete_booking_proto != nil {
		return
	}
	file_booking_v1_enums_booking_status_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_rpc_delete_booking_proto_rawDesc), len(file_booking_v1_rpc_delete_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_booking_v1_rpc_delete_booking_proto_goTypes,
		DependencyIndexes: file_booking_v1_rpc_delete_booking_proto_depIdxs,
		MessageInfos:      file_booking_v1_rpc_delete_booking_proto_msgTypes,
	}.Build()
	File_booking_v1_rpc_delete_booking_proto = out.File
	file_booking_v1_rpc_delete_booking_proto_goTypes = nil
	file_booking_v1_rpc_delete_booking_proto_depIdxs = nil
}
