// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: booking/v1/rpc/get_unavailable_rooms.proto

package bookingv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUnavailableRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CitySlug      string                 `protobuf:"bytes,2,opt,name=city_slug,json=citySlug,proto3" json:"city_slug,omitempty"`
	HotelId       string                 `protobuf:"bytes,3,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	CheckIn       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	CheckOut      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=check_out,json=checkOut,proto3" json:"check_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnavailableRoomsRequest) Reset() {
	*x = GetUnavailableRoomsRequest{}
	mi := &file_booking_v1_rpc_get_unavailable_rooms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnavailableRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnavailableRoomsRequest) ProtoMessage() {}

func (x *GetUnavailableRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_rpc_get_unavailable_rooms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnavailableRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetUnavailableRoomsRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_rpc_get_unavailable_rooms_proto_rawDescGZIP(), []int{0}
}

func (x *GetUnavailableRoomsRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GetUnavailableRoomsRequest) GetCitySlug() string {
	if x != nil {
		return x.CitySlug
	}
	return ""
}

func (x *GetUnavailableRoomsRequest) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *GetUnavailableRoomsRequest) GetCheckIn() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *GetUnavailableRoomsRequest) GetCheckOut() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckOut
	}
	return nil
}

type GetUnavailableRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomIds       []string               `protobuf:"bytes,1,rep,name=room_ids,json=roomIds,proto3" json:"room_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnavailableRoomsResponse) Reset() {
	*x = GetUnavailableRoomsResponse{}
	mi := &file_booking_v1_rpc_get_unavailable_rooms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnavailableRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnavailableRoomsResponse) ProtoMessage() {}

func (x *GetUnavailableRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_rpc_get_unavailable_rooms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnavailableRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetUnavailableRoomsResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_rpc_get_unavailable_rooms_proto_rawDescGZIP(), []int{1}
}

func (x *GetUnavailableRoomsResponse) GetRoomIds() []string {
	if x != nil {
		return x.RoomIds
	}
	return nil
}

var File_booking_v1_rpc_get_unavailable_rooms_proto protoreflect.FileDescriptor

const file_booking_v1_rpc_get_unavailable_rooms_proto_rawDesc = "" +
	"\n" +
	"*booking/v1/rpc/get_unavailable_rooms.proto\x12\n" +
	"booking.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\x98\x03\n" +
	"\x1aGetUnavailableRoomsRequest\x124\n" +
	"\fcountry_code\x18\x01 \x01(\tB\x11\xbaH\x0er\f2\n" +
	"^[a-z]{2}$R\vcountryCode\x12<\n" +
	"\tcity_slug\x18\x02 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\bcitySlug\x12#\n" +
	"\bhotel_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\ahotelId\x12=\n" +
	"\bcheck_in\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\acheckIn\x12?\n" +
	"\tcheck_out\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\bcheckOut:a\xbaH^\x1a\\\n" +
	"\x18availability.dates.order\x12 check_out must be after check_in\x1a\x1ethis.check_out > this.check_in\"8\n" +
	"\x1bGetUnavailableRoomsResponse\x12\x19\n" +
	"\broom_ids\x18\x01 \x03(\tR\aroomIdsB\x1aZ\x18api/booking/v1;bookingv1b\x06proto3"

var (
	file_booking_v1_rpc_get_unavailable_rooms_proto_rawDescOnce sync.Once
	file_booking_v1_rpc_get_unavailable_rooms_proto_rawDescData []byte
)

func file_booking_v1_rpc_get_unavailable_rooms_proto_rawDescGZIP() []byte {
	file_booking_v1_rpc_get_unavailable_rooms_proto_rawDescOnce.Do(func() {
		file_booking_v1_rpc_get_unavailable_rooms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_rpc_get_unavailable_rooms_proto_rawDesc), len(file_booking_v1_rpc_get_unavailable_rooms_proto_rawDesc)))
	})
	return file_booking_v1_rpc_get_unavailable_rooms_proto_rawDescData
}

var file_booking_v1_rpc_get_unavailable_rooms_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_booking_v1_rpc_get_unavailable_rooms_proto_goTypes = []any{
	(*GetUnavailableRoomsRequest)(nil),  // 0: booking.v1.GetUnavailableRoomsRequest
	(*GetUnavailableRoomsResponse)(nil), // 1: booking.v1.GetUnavailableRoomsResponse
	(*timestamppb.Timestamp)(nil),       // 2: google.protobuf.Timestamp
}
var file_booking_v1_rpc_get_unavailable_rooms_proto_depIdxs = []int32{
	2, // 0: booking.v1.GetUnavailableRoomsRequest.check_in:type_name -> google.protobuf.Timestamp
	2, // 1: booking.v1.GetUnavailableRoomsRequest.check_out:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_booking_v1_rpc_get_unavailable_rooms_proto_init() }
func file_booking_v1_rpc_get_unavailable_rooms_proto_init() {
	if File_booking_v1_rpc_get_unavailable_rooms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_rpc_get_unavailable_rooms_proto_rawDesc), len(file_booking_v1_rpc_get_unavailable_rooms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_booking_v1_rpc_get_unavailable_rooms_proto_goTypes,
		DependencyIndexes: file_booking_v1_rpc_get_unavailable_rooms_proto_depIdxs,
		MessageInfos:      file_booking_v1_rpc_get_unavailable_rooms_proto_msgTypes,
	}.Build()
	File_booking_v1_rpc_get_unavailable_rooms_proto = out.File
	file_booking_v1_rpc_get_unavailable_rooms_proto_goTypes = nil
	file_booking_v1_rpc_get_unavailable_rooms_proto_depIdxs = nil
}
