// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: booking/v1/rpc/get_booking_rooms.proto

package bookingv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBookingRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRoomsRequest) Reset() {
	*x = GetBookingRoomsRequest{}
	mi := &file_booking_v1_rpc_get_booking_rooms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRoomsRequest) ProtoMessage() {}

func (x *GetBookingRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_rpc_get_booking_rooms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRoomsRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_rpc_get_booking_rooms_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookingRoomsRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type GetBookingRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingRooms  []*BookingRoomFullInfo `protobuf:"bytes,1,rep,name=booking_rooms,json=bookingRooms,proto3" json:"booking_rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRoomsResponse) Reset() {
	*x = GetBookingRoomsResponse{}
	mi := &file_booking_v1_rpc_get_booking_rooms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRoomsResponse) ProtoMessage() {}

func (x *GetBookingRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_rpc_get_booking_rooms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetBookingRoomsResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_rpc_get_booking_rooms_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookingRoomsResponse) GetBookingRooms() []*BookingRoomFullInfo {
	if x != nil {
		return x.BookingRooms
	}
	return nil
}

var File_booking_v1_rpc_get_booking_rooms_proto protoreflect.FileDescriptor

const file_booking_v1_rpc_get_booking_rooms_proto_rawDesc = "" +
	"\n" +
	"&booking/v1/rpc/get_booking_rooms.proto\x12\n" +
	"booking.v1\x1a\x1bbuf/validate/validate.proto\x1a$booking/v1/models/booking_room.proto\x1a!booking/v1/models/room_lock.proto\"A\n" +
	"\x16GetBookingRoomsRequest\x12'\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tbookingId\"_\n" +
	"\x17GetBookingRoomsResponse\x12D\n" +
	"\rbooking_rooms\x18\x01 \x03(\v2\x1f.booking.v1.BookingRoomFullInfoR\fbookingRoomsB\x1aZ\x18api/booking/v1;bookingv1b\x06proto3"

var (
	file_booking_v1_rpc_get_booking_rooms_proto_rawDescOnce sync.Once
	file_booking_v1_rpc_get_booking_rooms_proto_rawDescData []byte
)

func file_booking_v1_rpc_get_booking_rooms_proto_rawDescGZIP() []byte {
	file_booking_v1_rpc_get_booking_rooms_proto_rawDescOnce.Do(func() {
		file_booking_v1_rpc_get_booking_rooms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_rpc_get_booking_rooms_proto_rawDesc), len(file_booking_v1_rpc_get_booking_rooms_proto_rawDesc)))
	})
	return file_booking_v1_rpc_get_booking_rooms_proto_rawDescData
}

var file_booking_v1_rpc_get_booking_rooms_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_booking_v1_rpc_get_booking_rooms_proto_goTypes = []any{
	(*GetBookingRoomsRequest)(nil),  // 0: booking.v1.GetBookingRoomsRequest
	(*GetBookingRoomsResponse)(nil), // 1: booking.v1.GetBookingRoomsResponse
	(*BookingRoomFullInfo)(nil),     // 2: booking.v1.BookingRoomFullInfo
}
var file_booking_v1_rpc_get_booking_rooms_proto_depIdxs = []int32{
	2, // 0: booking.v1.GetBookingRoomsResponse.booking_rooms:type_name -> booking.v1.BookingRoomFullInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_booking_v1_rpc_get_booking_rooms_proto_init() }
func file_booking_v1_rpc_get_booking_rooms_proto_init() {
	if File_booking_v1_rpc_get_booking_rooms_proto != nil {
		return
	}
	file_booking_v1_models_booking_room_proto_init()
	file_booking_v1_models_room_lock_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_rpc_get_booking_rooms_proto_rawDesc), len(file_booking_v1_rpc_get_booking_rooms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_booking_v1_rpc_get_booking_rooms_proto_goTypes,
		DependencyIndexes: file_booking_v1_rpc_get_booking_rooms_proto_depIdxs,
		MessageInfos:      file_booking_v1_rpc_get_booking_rooms_proto_msgTypes,
	}.Build()
	File_booking_v1_rpc_get_booking_rooms_proto = out.File
	file_booking_v1_rpc_get_booking_rooms_proto_goTypes = nil
	file_booking_v1_rpc_get_booking_rooms_proto_depIdxs = nil
}
