// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: booking/v1/rpc/get_bookings.proto

package bookingv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HotelId       string                 `protobuf:"bytes,2,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	Status        BookingStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=booking.v1.BookingStatus" json:"status,omitempty"`
	Page          uint64                 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint64                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingsRequest) Reset() {
	*x = GetBookingsRequest{}
	mi := &file_booking_v1_rpc_get_bookings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingsRequest) ProtoMessage() {}

func (x *GetBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_rpc_get_bookings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingsRequest.ProtoReflect.Descriptor instead.
func (*GetBookingsRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_rpc_get_bookings_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookingsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetBookingsRequest) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *GetBookingsRequest) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

func (x *GetBookingsRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBookingsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*BookingShort        `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint64                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingsResponse) Reset() {
	*x = GetBookingsResponse{}
	mi := &file_booking_v1_rpc_get_bookings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingsResponse) ProtoMessage() {}

func (x *GetBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_rpc_get_bookings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingsResponse.ProtoReflect.Descriptor instead.
func (*GetBookingsResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_rpc_get_bookings_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookingsResponse) GetBookings() []*BookingShort {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *GetBookingsResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetBookingsResponse) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBookingsResponse) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_booking_v1_rpc_get_bookings_proto protoreflect.FileDescriptor

const file_booking_v1_rpc_get_bookings_proto_rawDesc = "" +
	"\n" +
	"!booking/v1/rpc/get_bookings.proto\x12\n" +
	"booking.v1\x1a\x1bbuf/validate/validate.proto\x1a%booking/v1/enums/booking_status.proto\x1a\x1fbooking/v1/models/booking.proto\"\xe0\x01\n" +
	"\x12GetBookingsRequest\x12#\n" +
	"\auser_id\x18\x01 \x01(\x03B\n" +
	"\xbaH\a\xc8\x01\x01\"\x02 \x00R\x06userId\x12&\n" +
	"\bhotel_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\ahotelId\x129\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.booking.v1.BookingStatusB\x06\xbaH\x03\xc8\x01\x01R\x06status\x12\x1e\n" +
	"\x04page\x18\x04 \x01(\x04B\n" +
	"\xbaH\a\xc8\x01\x012\x02(\x01R\x04page\x12\"\n" +
	"\x05limit\x18\x05 \x01(\x04B\f\xbaH\t\xc8\x01\x012\x04\x18d(\x01R\x05limit\"\x96\x01\n" +
	"\x13GetBookingsResponse\x124\n" +
	"\bbookings\x18\x01 \x03(\v2\x18.booking.v1.BookingShortR\bbookings\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x04R\x05limitB\x1aZ\x18api/booking/v1;bookingv1b\x06proto3"

var (
	file_booking_v1_rpc_get_bookings_proto_rawDescOnce sync.Once
	file_booking_v1_rpc_get_bookings_proto_rawDescData []byte
)

func file_booking_v1_rpc_get_bookings_proto_rawDescGZIP() []byte {
	file_booking_v1_rpc_get_bookings_proto_rawDescOnce.Do(func() {
		file_booking_v1_rpc_get_bookings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_rpc_get_bookings_proto_rawDesc), len(file_booking_v1_rpc_get_bookings_proto_rawDesc)))
	})
	return file_booking_v1_rpc_get_bookings_proto_rawDescData
}

var file_booking_v1_rpc_get_bookings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_booking_v1_rpc_get_bookings_proto_goTypes = []any{
	(*GetBookingsRequest)(nil),  // 0: booking.v1.GetBookingsRequest
	(*GetBookingsResponse)(nil), // 1: booking.v1.GetBookingsResponse
	(BookingStatus)(0),          // 2: booking.v1.BookingStatus
	(*BookingShort)(nil),        // 3: booking.v1.BookingShort
}
var file_booking_v1_rpc_get_bookings_proto_depIdxs = []int32{
	2, // 0: booking.v1.GetBookingsRequest.status:type_name -> booking.v1.BookingStatus
	3, // 1: booking.v1.GetBookingsResponse.bookings:type_name -> booking.v1.BookingShort
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_booking_v1_rpc_get_bookings_proto_init() }
func file_booking_v1_rpc_get_bookings_proto_init() {
	if File_booking_v1_rpc_get_bookings_proto != nil {
		return
	}
	file_booking_v1_enums_booking_status_proto_init()
	file_booking_v1_models_booking_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_rpc_get_bookings_proto_rawDesc), len(file_booking_v1_rpc_get_bookings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_booking_v1_rpc_get_bookings_proto_goTypes,
		DependencyIndexes: file_booking_v1_rpc_get_bookings_proto_depIdxs,
		MessageInfos:      file_booking_v1_rpc_get_bookings_proto_msgTypes,
	}.Build()
	File_booking_v1_rpc_get_bookings_proto = out.File
	file_booking_v1_rpc_get_bookings_proto_goTypes = nil
	file_booking_v1_rpc_get_bookings_proto_depIdxs = nil
}
