// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: booking/v1/rpc/quote_booking.proto

package bookingv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuoteBookingRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	CountryCode   string                      `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CitySlug      string                      `protobuf:"bytes,2,opt,name=city_slug,json=citySlug,proto3" json:"city_slug,omitempty"`
	HotelId       string                      `protobuf:"bytes,3,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	CheckIn       *timestamppb.Timestamp      `protobuf:"bytes,4,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	CheckOut      *timestamppb.Timestamp      `protobuf:"bytes,5,opt,name=check_out,json=checkOut,proto3" json:"check_out,omitempty"`
	Currency      string                      `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Rooms         []*CreateBookingRoomRequest `protobuf:"bytes,7,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteBookingRequest) Reset() {
	*x = QuoteBookingRequest{}
	mi := &file_booking_v1_rpc_quote_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteBookingRequest) ProtoMessage() {}

func (x *QuoteBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_rpc_quote_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteBookingRequest.ProtoReflect.Descriptor instead.
func (*QuoteBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_rpc_quote_booking_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteBookingRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *QuoteBookingRequest) GetCitySlug() string {
	if x != nil {
		return x.CitySlug
	}
	return ""
}

func (x *QuoteBookingRequest) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *QuoteBookingRequest) GetCheckIn() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *QuoteBookingRequest) GetCheckOut() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckOut
	}
	return nil
}

func (x *QuoteBookingRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *QuoteBookingRequest) GetRooms() []*CreateBookingRoomRequest {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type QuoteBookingRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Adults        uint32                 `protobuf:"varint,2,opt,name=adults,proto3" json:"adults,omitempty"`
	Children      uint32                 `protobuf:"varint,3,opt,name=children,proto3" json:"children,omitempty"`
	PricePerNight string                 `protobuf:"bytes,4,opt,name=price_per_night,json=pricePerNight,proto3" json:"price_per_night,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteBookingRoom) Reset() {
	*x = QuoteBookingRoom{}
	mi := &file_booking_v1_rpc_quote_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteBookingRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteBookingRoom) ProtoMessage() {}

func (x *QuoteBookingRoom) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_rpc_quote_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteBookingRoom.ProtoReflect.Descriptor instead.
func (*QuoteBookingRoom) Descriptor() ([]byte, []int) {
	return file_booking_v1_rpc_quote_booking_proto_rawDescGZIP(), []int{1}
}

func (x *QuoteBookingRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *QuoteBookingRoom) GetAdults() uint32 {
	if x != nil {
		return x.Adults
	}
	return 0
}

func (x *QuoteBookingRoom) GetChildren() uint32 {
	if x != nil {
		return x.Children
	}
	return 0
}

func (x *QuoteBookingRoom) GetPricePerNight() string {
	if x != nil {
		return x.PricePerNight
	}
	return ""
}

func (x *QuoteBookingRoom) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

type QuoteBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckIn       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	CheckOut      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=check_out,json=checkOut,proto3" json:"check_out,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Nights        uint32                 `protobuf:"varint,5,opt,name=nights,proto3" json:"nights,omitempty"`
	Rooms         []*QuoteBookingRoom    `protobuf:"bytes,6,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteBookingResponse) Reset() {
	*x = QuoteBookingResponse{}
	mi := &file_booking_v1_rpc_quote_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteBookingResponse) ProtoMessage() {}

func (x *QuoteBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_rpc_quote_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteBookingResponse.ProtoReflect.Descriptor instead.
func (*QuoteBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_rpc_quote_booking_proto_rawDescGZIP(), []int{2}
}

func (x *QuoteBookingResponse) GetCheckIn() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *QuoteBookingResponse) GetCheckOut() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckOut
	}
	return nil
}

func (x *QuoteBookingResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *QuoteBookingResponse) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *QuoteBookingResponse) GetNights() uint32 {
	if x != nil {
		return x.Nights
	}
	return 0
}

func (x *QuoteBookingResponse) GetRooms() []*QuoteBookingRoom {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_booking_v1_rpc_quote_booking_proto protoreflect.FileDescriptor

const file_booking_v1_rpc_quote_booking_proto_rawDesc = "" +
	"\n" +
	"\"booking/v1/rpc/quote_booking.proto\x12\n" +
	"booking.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\x1a#booking/v1/rpc/create_booking.proto\"\x8c\x04\n" +
	"\x13QuoteBookingRequest\x124\n" +
	"\fcountry_code\x18\x01 \x01(\tB\x11\xbaH\x0er\f2\n" +
	"^[a-z]{2}$R\vcountryCode\x12<\n" +
	"\tcity_slug\x18\x02 \x01(\tB\x1f\xbaH\x1cr\x1a2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\bcitySlug\x12#\n" +
	"\bhotel_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\ahotelId\x12B\n" +
	"\bcheck_in\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\v\xbaH\b\xc8\x01\x01\xb2\x01\x02@\x01R\acheckIn\x12?\n" +
	"\tcheck_out\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\bcheckOut\x12-\n" +
	"\bcurrency\x18\x06 \x01(\tB\x11\xbaH\x0er\f2\n" +
	"^[A-Z]{3}$R\bcurrency\x12D\n" +
	"\x05rooms\x18\a \x03(\v2$.booking.v1.CreateBookingRoomRequestB\b\xbaH\x05\x92\x01\x02\b\x01R\x05rooms:b\xbaH_\x1a]\n" +
	"\x19booking_quote.dates.order\x12 check_out must be after check_in\x1a\x1ethis.check_out > this.check_in\"\xaa\x01\n" +
	"\x10QuoteBookingRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06adults\x18\x02 \x01(\rR\x06adults\x12\x1a\n" +
	"\bchildren\x18\x03 \x01(\rR\bchildren\x12&\n" +
	"\x0fprice_per_night\x18\x04 \x01(\tR\rpricePerNight\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\tR\vtotalAmount\"\x91\x02\n" +
	"\x14QuoteBookingResponse\x125\n" +
	"\bcheck_in\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\acheckIn\x127\n" +
	"\tcheck_out\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bcheckOut\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\tR\vtotalAmount\x12\x16\n" +
	"\x06nights\x18\x05 \x01(\rR\x06nights\x122\n" +
	"\x05rooms\x18\x06 \x03(\v2\x1c.booking.v1.QuoteBookingRoomR\x05roomsB\x1aZ\x18api/booking/v1;bookingv1b\x06proto3"

var (
	file_booking_v1_rpc_quote_booking_proto_rawDescOnce sync.Once
	file_booking_v1_rpc_quote_booking_proto_rawDescData []byte
)

func file_booking_v1_rpc_quote_booking_proto_rawDescGZIP() []byte {
	file_booking_v1_rpc_quote_booking_proto_rawDescOnce.Do(func() {
		file_booking_v1_rpc_quote_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_rpc_quote_booking_proto_rawDesc), len(file_booking_v1_rpc_quote_booking_proto_rawDesc)))
	})
	return file_booking_v1_rpc_quote_booking_proto_rawDescData
}

var file_booking_v1_rpc_quote_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_booking_v1_rpc_quote_booking_proto_goTypes = []any{
	(*QuoteBookingRequest)(nil),      // 0: booking.v1.QuoteBookingRequest
	(*QuoteBookingRoom)(nil),         // 1: booking.v1.QuoteBookingRoom
	(*QuoteBookingResponse)(nil),     // 2: booking.v1.QuoteBookingResponse
	(*timestamppb.Timestamp)(nil),    // 3: google.protobuf.Timestamp
	(*CreateBookingRoomRequest)(nil), // 4: booking.v1.CreateBookingRoomRequest
}
var file_booking_v1_rpc_quote_booking_proto_depIdxs = []int32{
	3, // 0: booking.v1.QuoteBookingRequest.check_in:type_name -> google.protobuf.Timestamp
	3, // 1: booking.v1.QuoteBookingRequest.check_out:type_name -> google.protobuf.Timestamp
	4, // 2: booking.v1.QuoteBookingRequest.rooms:type_name -> booking.v1.CreateBookingRoomRequest
	3, // 3: booking.v1.QuoteBookingResponse.check_in:type_name -> google.protobuf.Timestamp
	3, // 4: booking.v1.QuoteBookingResponse.check_out:type_name -> google.protobuf.Timestamp
	1, // 5: booking.v1.QuoteBookingResponse.rooms:type_name -> booking.v1.QuoteBookingRoom
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_booking_v1_rpc_quote_booking_proto_init() }
func file_booking_v1_rpc_quote_booking_proto_init() {
	if File_booking_v1_rpc_quote_booking_proto != nil {
		return
	}
	file_booking_v1_rpc_create_booking_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_rpc_quote_booking_proto_rawDesc), len(file_booking_v1_rpc_quote_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_booking_v1_rpc_quote_booking_proto_goTypes,
		DependencyIndexes: file_booking_v1_rpc_quote_booking_proto_depIdxs,
		MessageInfos:      file_booking_v1_rpc_quote_booking_proto_msgTypes,
	}.Build()
	File_booking_v1_rpc_quote_booking_proto = out.File
	file_booking_v1_rpc_quote_booking_proto_goTypes = nil
	file_booking_v1_rpc_quote_booking_proto_depIdxs = nil
}
